In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import brute
plt.style.use("seaborn-v0_8")

In [2]:
from FindingBacktester import FindingBacktester

In [3]:
filepath = "./data/one_minute.csv"  # Updated to correct relative path
symbol = "GBPUSD"

start1 = "2018-01-01"
end1 = "2018-03-31"
start2 = "2018-04-01"
end2 = "2018-06-30"
start3 = "2018-07-01"
end3 = "2018-09-30"
start4 = "2018-10-01"
end4 = "2018-12-31"

end5 = "2019-06-30"

ptc = 0.00007

In [4]:
tester = FindingBacktester(ptc, "GBP_USD")

In [5]:
tester.download_recent_data("GBP_USD", 100000, "GBP_recent_data_1.csv", "H1")

In [6]:
tester.data

,price,Open,High,Low,Close,spread,returns
time,,,,,,,
2009-09-30 15:00:00,1.60037,1.59933,1.60091,1.59640,1.60037,0.00018,-0.016995
2009-09-30 16:00:00,1.60160,1.60032,1.60287,1.60029,1.60160,0.00018,0.000768
2009-09-30 17:00:00,1.59910,1.60156,1.60238,1.59829,1.59910,0.00018,-0.001562
2009-09-30 18:00:00,1.60059,1.59906,1.60138,1.59842,1.60059,0.00018,0.000931
2009-09-30 19:00:00,1.59802,1.60062,1.60094,1.59732,1.59802,0.00018,-0.001607
...,...,...,...,...,...,...,...
2025-07-29 09:00:00,1.33538,1.33418,1.33590,1.33418,1.33538,0.00021,0.000907
2025-07-29 10:00:00,1.33503,1.33538,1.33618,1.33498,1.33503,0.00018,-0.000262
2025-07-29 11:00:00,1.33402,1.33505,1.33529,1.33272,1.33402,0.00015,-0.000757
2025-07-29 12:00:00,1.33154,1.33402,1.33438,1.33154,1.33154,0.00020,-0.001861
2025-07-29 13:00:00,1.33123,1.33154,1.33210,1.33078,1.33123,0.00020,-0.000233

In [7]:
tester.prepare_data_EMA_SMA(10,50)

In [8]:
tester.prepare_data_RSI(20, 70, 30)

In [9]:
tester.data

,price,Open,High,Low,Close,spread,returns,EMA_S,EMA_L,U,D,MA_U,MA_D,RSI
time,,,,,,,,,,,,,,
2009-09-30 15:00:00,1.60037,1.59933,1.60091,1.59640,1.60037,0.00018,-0.016995,NaN,NaN,0.00000,0.00000,NaN,NaN,NaN
2009-09-30 16:00:00,1.60160,1.60032,1.60287,1.60029,1.60160,0.00018,0.000768,NaN,NaN,0.00123,0.00000,NaN,NaN,NaN
2009-09-30 17:00:00,1.59910,1.60156,1.60238,1.59829,1.59910,0.00018,-0.001562,NaN,NaN,0.00000,0.00250,NaN,NaN,NaN
2009-09-30 18:00:00,1.60059,1.59906,1.60138,1.59842,1.60059,0.00018,0.000931,NaN,NaN,0.00149,0.00000,NaN,NaN,NaN
2009-09-30 19:00:00,1.59802,1.60062,1.60094,1.59732,1.59802,0.00018,-0.001607,NaN,NaN,0.00000,0.00257,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-07-29 09:00:00,1.33538,1.33418,1.33590,1.33418,1.33538,0.00021,0.000907,1.334751,1.340079,0.00121,0.00000,0.000266,0.000574,31.666667
2025-07-29 10:00:00,1.33503,1.33538,1.33618,1.33498,1.33503,0.00018,-0.000262,1.334802,1.339881,0.00000,0.00035,0.000266,0.000577,31.572700
2025-07-29 11:00:00,1.33402,1.33505,1.33529,1.33272,1.33402,0.00015,-0.000757,1.334659,1.339651,0.00000,0.00101,0.000266,0.000522,33.756345
2025-07-29 12:00:00,1.33154,1.33402,1.33438,1.33154,1.33154,0.00020,-0.001861,1.334092,1.339333,0.00000,0.00248,0.000266,0.000583,31.330978
2025-07-29 13:00:00,1.33123,1.33154,1.33210,1.33078,1.33123,0.00020,-0.000233,1.333572,1.339015,0.00000,0.00031,0.000266,0.000503,34.612882

In [10]:
tester.prepare_data_MACD(12, 26, 9)

In [11]:
tester.data

,price,Open,High,Low,Close,spread,returns,EMA_S,EMA_L,U,D,MA_U,MA_D,RSI,MACD_EMA_S,MACD_EMA_L,MACD,MACD_Signal
time,,,,,,,,,,,,,,,,,,
2009-09-30 15:00:00,1.60037,1.59933,1.60091,1.59640,1.60037,0.00018,-0.016995,NaN,NaN,0.00000,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009-09-30 16:00:00,1.60160,1.60032,1.60287,1.60029,1.60160,0.00018,0.000768,NaN,NaN,0.00123,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009-09-30 17:00:00,1.59910,1.60156,1.60238,1.59829,1.59910,0.00018,-0.001562,NaN,NaN,0.00000,0.00250,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009-09-30 18:00:00,1.60059,1.59906,1.60138,1.59842,1.60059,0.00018,0.000931,NaN,NaN,0.00149,0.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009-09-30 19:00:00,1.59802,1.60062,1.60094,1.59732,1.59802,0.00018,-0.001607,NaN,NaN,0.00000,0.00257,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-07-29 09:00:00,1.33538,1.33418,1.33590,1.33418,1.33538,0.00021,0.000907,1.334751,1.340079,0.00121,0.00000,0.000266,0.000574,31.666667,1.334979,1.336967,-0.001987,-0.002206
2025-07-29 10:00:00,1.33503,1.33538,1.33618,1.33498,1.33503,0.00018,-0.000262,1.334802,1.339881,0.00000,0.00035,0.000266,0.000577,31.572700,1.334987,1.336823,-0.001836,-0.002132
2025-07-29 11:00:00,1.33402,1.33505,1.33529,1.33272,1.33402,0.00015,-0.000757,1.334659,1.339651,0.00000,0.00101,0.000266,0.000522,33.756345,1.334838,1.336616,-0.001777,-0.002061
2025-07-29 12:00:00,1.33154,1.33402,1.33438,1.33154,1.33154,0.00020,-0.001861,1.334092,1.339333,0.00000,0.00248,0.000266,0.000583,31.330978,1.334331,1.336240,-0.001909,-0.002031
2025-07-29 13:00:00,1.33123,1.33154,1.33210,1.33078,1.33123,0.00020,-0.000233,1.333572,1.339015,0.00000,0.00031,0.000266,0.000503,34.612882,1.333854,1.335869,-0.002015,-0.002027

In [12]:
tester.test_strategy()

====================================================================================================
EMA/SMA + RSI COMBINED STRATEGY | INSTRUMENT = GBP_USD
----------------------------------------------------------------------------------------------------
PERFORMANCE MEASURES:


Multiple (Strategy):         0.957435
Multiple (Buy-and-Hold):     1.183714
--------------------------------------
Out-/Underperformance:       -0.226279


CAGR:                        -0.002746
Annualized Mean:             -0.002753
Annualized Std:              0.00914
Sharpe Ratio:                -0.301142
Sortino Ratio:               -0.431214
Maximum Drawdown:            0.061176
Calmar Ratio:                -0.044885
Max Drawdown Duration:       4861 Days
Kelly Criterion:             -32.431343
====================================================================================================

(0.957435, -0.226279)

In [ ]:
tester.plot_results()

1. Testing MACD

In [13]:
tester.optimize_parameters_optuna(EMA1_range=(20, 100, 1), EMA2_range=(20, 100, 1), periods_range=(5, 20, 1), rsi_upper_range=(65, 80, 1),rsi_lower_range=(20, 35, 1), metric="Multiple", n_trials=1000, mode="macd")

[I 2025-07-29 20:52:13,239] A new study created in memory with name: no-name-51d88a41-63e3-4c04-aa87-44ec5e282f39
[I 2025-07-29 20:52:13,309] Trial 0 finished with value: -0.39699588575722733 and parameters: {'EMA_S': 57, 'EMA_L': 55, 'signal_mw': 14}. Best is trial 0 with value: -0.39699588575722733.
[I 2025-07-29 20:52:13,359] Trial 1 finished with value: -0.4275161046839223 and parameters: {'EMA_S': 42, 'EMA_L': 27, 'signal_mw': 15}. Best is trial 1 with value: -0.4275161046839223.
[I 2025-07-29 20:52:13,408] Trial 2 finished with value: -0.9804015412831866 and parameters: {'EMA_S': 62, 'EMA_L': 73, 'signal_mw': 10}. Best is trial 2 with value: -0.9804015412831866.
[I 2025-07-29 20:52:13,456] Trial 3 finished with value: -0.4634282697948198 and parameters: {'EMA_S': 49, 'EMA_L': 45, 'signal_mw': 18}. Best is trial 2 with value: -0.9804015412831866.
[I 2025-07-29 20:52:13,513] Trial 4 finished with value: -1.1834625196284911 and parameters: {'EMA_S': 47, 'EMA_L': 76, 'signal_mw': 19}. Best is trial 4 with value: -1.1834625196284911.
[I 2025-07-29 20:52:13,562] Trial 5 finished with value: -0.41728159998121245 and parameters: {'EMA_S': 75, 'EMA_L': 63, 'signal_mw': 14}. Best is trial 4 with value: -1.1834625196284911.
[I 2025-07-29 20:52:13,613] Trial 6 finished with value: -0.4059862626915797 and parameters: {'EMA_S': 66, 'EMA_L': 59, 'signal_mw': 5}. Best is trial 4 with value: -1.1834625196284911.
[I 2025-07-29 20:52:13,663] Trial 7 finished with value: -0.36506663989181354 and parameters: {'EMA_S': 91, 'EMA_L': 55, 'signal_mw': 15}. Best is trial 4 with value: -1.1834625196284911.
[I 2025-07-29 20:52:13,779] Trial 8 finished with value: -0.6467418795072659 and parameters: {'EMA_S': 89, 'EMA_L': 74, 'signal_mw': 19}. Best is trial 4 with value: -1.1834625196284911.
[I 2025-07-29 20:52:13,857] Trial 9 finished with value: -0.8447986087876714 and parameters: {'EMA_S': 28, 'EMA_L': 28, 'signal_mw': 15}. Best is trial 4 with value: -1.1834625196284911.
[I 2025-07-29 20:52:13,918] Trial 10 finished with value: -0.9826498233089184 and parameters: {'EMA_S': 20, 'EMA_L': 94, 'signal_mw': 20}. Best is trial 4 with value: -1.1834625196284911.
[I 2025-07-29 20:52:13,989] Trial 11 finished with value: -0.9073398052151654 and parameters: {'EMA_S': 20, 'EMA_L': 99, 'signal_mw': 20}. Best is trial 4 with value: -1.1834625196284911.
[I 2025-07-29 20:52:14,054] Trial 12 finished with value: -1.1512264841069968 and parameters: {'EMA_S': 35, 'EMA_L': 98, 'signal_mw': 18}. Best is trial 4 with value: -1.1834625196284911.
[I 2025-07-29 20:52:14,123] Trial 13 finished with value: -1.0884484463268098 and parameters: {'EMA_S': 39, 'EMA_L': 86, 'signal_mw': 17}. Best is trial 4 with value: -1.1834625196284911.
[I 2025-07-29 20:52:14,185] Trial 14 finished with value: -0.8752684844803096 and parameters: {'EMA_S': 34, 'EMA_L': 83, 'signal_mw': 11}. Best is trial 4 with value: -1.1834625196284911.
[I 2025-07-29 20:52:14,236] Trial 15 finished with value: -1.3160887507201995 and parameters: {'EMA_S': 50, 'EMA_L': 88, 'signal_mw': 17}. Best is trial 15 with value: -1.3160887507201995.
[I 2025-07-29 20:52:14,308] Trial 16 finished with value: -1.0085109455647636 and parameters: {'EMA_S': 52, 'EMA_L': 77, 'signal_mw': 8}. Best is trial 15 with value: -1.3160887507201995.
[I 2025-07-29 20:52:14,370] Trial 17 finished with value: -0.8616724034274774 and parameters: {'EMA_S': 72, 'EMA_L': 86, 'signal_mw': 17}. Best is trial 15 with value: -1.3160887507201995.
[I 2025-07-29 20:52:14,443] Trial 18 finished with value: -0.920238330749338 and parameters: {'EMA_S': 48, 'EMA_L': 70, 'signal_mw': 12}. Best is trial 15 with value: -1.3160887507201995.
[I 2025-07-29 20:52:14,508] Trial 19 finished with value: -0.44984693336148596 and parameters: {'EMA_S': 45, 'EMA_L': 44, 'signal_mw': 17}. Best is trial 15 with value: -1.3160887507201995.
[I 2025-07-29 20:52:14,574] Trial 20 finished with value: -0.7671324091427033 and parameters: {'EMA_S': 83, 'EMA_L': 91, 'signal_mw': 20}. Best is trial 15 with value: -1.3160887507201995.
[I 2025-07-29 20:52:14,646] Trial 21 finished with value: -1.3746885332955168 and parameters: {'EMA_S': 31, 'EMA_L': 98, 'signal_mw': 18}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:14,740] Trial 22 finished with value: -1.125092245175357 and parameters: {'EMA_S': 29, 'EMA_L': 82, 'signal_mw': 18}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:14,842] Trial 23 finished with value: -1.2499561072712249 and parameters: {'EMA_S': 55, 'EMA_L': 89, 'signal_mw': 16}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:14,931] Trial 24 finished with value: -1.2578378619140198 and parameters: {'EMA_S': 57, 'EMA_L': 91, 'signal_mw': 16}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:15,013] Trial 25 finished with value: -1.1824323872509095 and parameters: {'EMA_S': 63, 'EMA_L': 94, 'signal_mw': 13}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:15,087] Trial 26 finished with value: -0.5423621705601898 and parameters: {'EMA_S': 98, 'EMA_L': 67, 'signal_mw': 17}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:15,166] Trial 27 finished with value: -1.1543680191445544 and parameters: {'EMA_S': 67, 'EMA_L': 81, 'signal_mw': 16}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:15,244] Trial 28 finished with value: -0.9715556006693226 and parameters: {'EMA_S': 27, 'EMA_L': 99, 'signal_mw': 16}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:15,321] Trial 29 finished with value: -1.210714073956471 and parameters: {'EMA_S': 57, 'EMA_L': 92, 'signal_mw': 13}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:15,394] Trial 30 finished with value: -0.8585592028773839 and parameters: {'EMA_S': 36, 'EMA_L': 42, 'signal_mw': 14}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:15,479] Trial 31 finished with value: -1.3271127138759145 and parameters: {'EMA_S': 54, 'EMA_L': 89, 'signal_mw': 16}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:15,552] Trial 32 finished with value: -1.0985468088296781 and parameters: {'EMA_S': 57, 'EMA_L': 88, 'signal_mw': 19}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:15,625] Trial 33 finished with value: -1.1036895950887295 and parameters: {'EMA_S': 42, 'EMA_L': 79, 'signal_mw': 15}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:15,692] Trial 34 finished with value: -1.1781617925321717 and parameters: {'EMA_S': 52, 'EMA_L': 94, 'signal_mw': 18}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:15,779] Trial 35 finished with value: -1.159098571013222 and parameters: {'EMA_S': 61, 'EMA_L': 88, 'signal_mw': 16}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:15,849] Trial 36 finished with value: -1.0470493774783967 and parameters: {'EMA_S': 43, 'EMA_L': 95, 'signal_mw': 9}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:15,926] Trial 37 finished with value: -1.1810594321361463 and parameters: {'EMA_S': 68, 'EMA_L': 71, 'signal_mw': 14}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:15,985] Trial 38 finished with value: -1.125908968159339 and parameters: {'EMA_S': 78, 'EMA_L': 84, 'signal_mw': 12}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:16,049] Trial 39 finished with value: -0.44765885444739467 and parameters: {'EMA_S': 49, 'EMA_L': 21, 'signal_mw': 19}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:16,116] Trial 40 finished with value: -1.1729589350235174 and parameters: {'EMA_S': 60, 'EMA_L': 66, 'signal_mw': 17}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:16,185] Trial 41 finished with value: -1.3259616978278514 and parameters: {'EMA_S': 53, 'EMA_L': 90, 'signal_mw': 16}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:16,249] Trial 42 finished with value: -1.241405353330268 and parameters: {'EMA_S': 53, 'EMA_L': 90, 'signal_mw': 15}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:16,316] Trial 43 finished with value: -0.39885395273432755 and parameters: {'EMA_S': 65, 'EMA_L': 49, 'signal_mw': 16}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:16,402] Trial 44 finished with value: -0.8785470750948062 and parameters: {'EMA_S': 71, 'EMA_L': 96, 'signal_mw': 5}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:16,466] Trial 45 finished with value: -1.0847633861062411 and parameters: {'EMA_S': 45, 'EMA_L': 76, 'signal_mw': 18}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:16,525] Trial 46 finished with value: -1.337296880228474 and parameters: {'EMA_S': 38, 'EMA_L': 85, 'signal_mw': 14}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:16,582] Trial 47 finished with value: -0.9010993485888956 and parameters: {'EMA_S': 31, 'EMA_L': 79, 'signal_mw': 14}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:16,649] Trial 48 finished with value: -0.8173579615320836 and parameters: {'EMA_S': 24, 'EMA_L': 85, 'signal_mw': 15}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:16,719] Trial 49 finished with value: -1.2666445973141447 and parameters: {'EMA_S': 39, 'EMA_L': 97, 'signal_mw': 19}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:16,792] Trial 50 finished with value: -1.1374777274007581 and parameters: {'EMA_S': 39, 'EMA_L': 87, 'signal_mw': 13}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:16,869] Trial 51 finished with value: -1.2939547444244042 and parameters: {'EMA_S': 39, 'EMA_L': 99, 'signal_mw': 19}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:16,928] Trial 52 finished with value: -1.183746201803742 and parameters: {'EMA_S': 35, 'EMA_L': 99, 'signal_mw': 19}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:16,992] Trial 53 finished with value: -1.231146343278592 and parameters: {'EMA_S': 49, 'EMA_L': 93, 'signal_mw': 18}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:17,059] Trial 54 finished with value: -1.0530358437196434 and parameters: {'EMA_S': 32, 'EMA_L': 96, 'signal_mw': 20}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:17,120] Trial 55 finished with value: -0.9104820188475329 and parameters: {'EMA_S': 24, 'EMA_L': 82, 'signal_mw': 17}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:17,182] Trial 56 finished with value: -1.316388937947793 and parameters: {'EMA_S': 43, 'EMA_L': 59, 'signal_mw': 17}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:17,249] Trial 57 finished with value: -0.6023312096254024 and parameters: {'EMA_S': 47, 'EMA_L': 60, 'signal_mw': 7}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:17,316] Trial 58 finished with value: -1.0755667868415963 and parameters: {'EMA_S': 54, 'EMA_L': 62, 'signal_mw': 17}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:17,382] Trial 59 finished with value: -0.9125498983544523 and parameters: {'EMA_S': 43, 'EMA_L': 49, 'signal_mw': 15}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:17,435] Trial 60 finished with value: -0.9351425611151274 and parameters: {'EMA_S': 45, 'EMA_L': 54, 'signal_mw': 16}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:17,516] Trial 61 finished with value: -0.9540733833201502 and parameters: {'EMA_S': 37, 'EMA_L': 55, 'signal_mw': 18}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:17,592] Trial 62 finished with value: -0.4174397013105872 and parameters: {'EMA_S': 40, 'EMA_L': 38, 'signal_mw': 20}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:17,659] Trial 63 finished with value: -1.2322040573934705 and parameters: {'EMA_S': 32, 'EMA_L': 91, 'signal_mw': 17}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:17,715] Trial 64 finished with value: -1.1074677161062727 and parameters: {'EMA_S': 50, 'EMA_L': 86, 'signal_mw': 19}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:17,782] Trial 65 finished with value: -1.1507642734158665 and parameters: {'EMA_S': 41, 'EMA_L': 93, 'signal_mw': 18}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:17,850] Trial 66 finished with value: -1.076996691968213 and parameters: {'EMA_S': 46, 'EMA_L': 74, 'signal_mw': 16}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:17,925] Trial 67 finished with value: -1.10001772694242 and parameters: {'EMA_S': 37, 'EMA_L': 99, 'signal_mw': 15}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:17,992] Trial 68 finished with value: -1.1914440742319194 and parameters: {'EMA_S': 51, 'EMA_L': 90, 'signal_mw': 18}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:18,096] Trial 69 finished with value: -1.0743092654119135 and parameters: {'EMA_S': 55, 'EMA_L': 66, 'signal_mw': 17}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:18,215] Trial 70 finished with value: -0.8615479764937254 and parameters: {'EMA_S': 28, 'EMA_L': 80, 'signal_mw': 14}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:18,282] Trial 71 finished with value: -1.188770027473037 and parameters: {'EMA_S': 39, 'EMA_L': 95, 'signal_mw': 19}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:18,349] Trial 72 finished with value: -1.1472015658111234 and parameters: {'EMA_S': 34, 'EMA_L': 97, 'signal_mw': 20}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:18,426] Trial 73 finished with value: -1.3311679010724073 and parameters: {'EMA_S': 44, 'EMA_L': 97, 'signal_mw': 19}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:18,493] Trial 74 finished with value: -1.1907764152408653 and parameters: {'EMA_S': 58, 'EMA_L': 89, 'signal_mw': 17}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:18,549] Trial 75 finished with value: -1.0681262043747015 and parameters: {'EMA_S': 44, 'EMA_L': 93, 'signal_mw': 11}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:18,616] Trial 76 finished with value: -1.2684693560089724 and parameters: {'EMA_S': 47, 'EMA_L': 97, 'signal_mw': 18}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:18,682] Trial 77 finished with value: -1.0802034389254878 and parameters: {'EMA_S': 41, 'EMA_L': 83, 'signal_mw': 16}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:18,753] Trial 78 finished with value: -1.0921281236434037 and parameters: {'EMA_S': 50, 'EMA_L': 58, 'signal_mw': 19}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:18,832] Trial 79 finished with value: -1.1461985850129808 and parameters: {'EMA_S': 53, 'EMA_L': 88, 'signal_mw': 18}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:18,909] Trial 80 finished with value: -1.3402581043725446 and parameters: {'EMA_S': 59, 'EMA_L': 92, 'signal_mw': 15}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:18,976] Trial 81 finished with value: -1.3402581043725446 and parameters: {'EMA_S': 59, 'EMA_L': 92, 'signal_mw': 15}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:19,042] Trial 82 finished with value: -1.1595843138001765 and parameters: {'EMA_S': 63, 'EMA_L': 92, 'signal_mw': 15}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:19,108] Trial 83 finished with value: -1.298506124125986 and parameters: {'EMA_S': 57, 'EMA_L': 85, 'signal_mw': 15}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:19,182] Trial 84 finished with value: -1.1508545652474116 and parameters: {'EMA_S': 61, 'EMA_L': 95, 'signal_mw': 14}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:19,259] Trial 85 finished with value: -1.236214944653346 and parameters: {'EMA_S': 59, 'EMA_L': 90, 'signal_mw': 13}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:19,328] Trial 86 finished with value: -1.3212483238036625 and parameters: {'EMA_S': 55, 'EMA_L': 88, 'signal_mw': 16}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:19,392] Trial 87 finished with value: -1.0419433222090233 and parameters: {'EMA_S': 65, 'EMA_L': 86, 'signal_mw': 16}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:19,469] Trial 88 finished with value: -1.1522533117235207 and parameters: {'EMA_S': 63, 'EMA_L': 92, 'signal_mw': 14}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:19,532] Trial 89 finished with value: -1.1872859198471712 and parameters: {'EMA_S': 55, 'EMA_L': 84, 'signal_mw': 15}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:19,599] Trial 90 finished with value: -1.1489667062940463 and parameters: {'EMA_S': 69, 'EMA_L': 77, 'signal_mw': 16}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:19,666] Trial 91 finished with value: -1.309524307817849 and parameters: {'EMA_S': 52, 'EMA_L': 89, 'signal_mw': 17}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:19,735] Trial 92 finished with value: -1.265270395641094 and parameters: {'EMA_S': 56, 'EMA_L': 94, 'signal_mw': 16}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:19,799] Trial 93 finished with value: -1.1510619627300671 and parameters: {'EMA_S': 59, 'EMA_L': 88, 'signal_mw': 17}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:19,865] Trial 94 finished with value: -1.0931532499779992 and parameters: {'EMA_S': 48, 'EMA_L': 91, 'signal_mw': 15}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:19,979] Trial 95 finished with value: -0.3199202805101972 and parameters: {'EMA_S': 53, 'EMA_L': 52, 'signal_mw': 16}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:20,069] Trial 96 finished with value: -1.253992714615266 and parameters: {'EMA_S': 51, 'EMA_L': 97, 'signal_mw': 15}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:20,136] Trial 97 finished with value: -1.0451152631394727 and parameters: {'EMA_S': 43, 'EMA_L': 87, 'signal_mw': 17}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:20,216] Trial 98 finished with value: -1.250960425614059 and parameters: {'EMA_S': 48, 'EMA_L': 95, 'signal_mw': 16}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:20,282] Trial 99 finished with value: -1.0685453431778609 and parameters: {'EMA_S': 54, 'EMA_L': 82, 'signal_mw': 12}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:20,352] Trial 100 finished with value: -1.0627639361533754 and parameters: {'EMA_S': 61, 'EMA_L': 64, 'signal_mw': 14}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:20,425] Trial 101 finished with value: -1.3123744436518423 and parameters: {'EMA_S': 51, 'EMA_L': 90, 'signal_mw': 17}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:20,499] Trial 102 finished with value: -1.1993110732554482 and parameters: {'EMA_S': 56, 'EMA_L': 92, 'signal_mw': 17}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:20,575] Trial 103 finished with value: -1.0879779115323527 and parameters: {'EMA_S': 46, 'EMA_L': 90, 'signal_mw': 16}. Best is trial 21 with value: -1.3746885332955168.
[I 2025-07-29 20:52:20,643] Trial 104 finished with value: -1.2979548455521077 and parameters: {'EMA_S': 50, 'EMA_L': 87, 'signal_mw': 18}. Best is trial 21 with value: -1.3746885332955168.

Optuna optimization completed.
Best Parameters (MACD): EMA_S = 54, EMA_L = 86, signal_mw = 16
Best Multiple: 1.426697
====================================================================================================
MACD STRATEGY | INSTRUMENT = GBP_USD
----------------------------------------------------------------------------------------------------
PERFORMANCE MEASURES:


Multiple (Strategy):         1.426697
Multiple (Buy-and-Hold):     1.182033
--------------------------------------
Out-/Underperformance:       0.244664


CAGR:                        0.022734
Annualized Mean:             0.022499
Annualized Std:              0.122445
Sharpe Ratio:                0.183744
Sortino Ratio:               0.263831
Maximum Drawdown:            0.414493
Calmar Ratio:                0.054848
Max Drawdown Duration:       3997 Days
Kelly Criterion:             1.998659
====================================================================================================

In [16]:
tester.add_leverage(1)

====================================================================================================
EMA/SMA + RSI COMBINED STRATEGY | INSTRUMENT = GBP_USD
----------------------------------------------------------------------------------------------------
PERFORMANCE MEASURES:


Multiple (Strategy):         1.266457
Multiple (Buy-and-Hold):     1.182033
--------------------------------------
Out-/Underperformance:       0.084424


CAGR:                        0.015055
Annualized Mean:             0.014956
Annualized Std:              0.123096
Sharpe Ratio:                0.121497
Sortino Ratio:               0.16947
Maximum Drawdown:            0.43628
Calmar Ratio:                0.034508
Max Drawdown Duration:       4434 Days
Kelly Criterion:             1.500628
====================================================================================================

2. Testing MACD_RSI

In [17]:
tester.optimize_parameters_optuna(EMA1_range=(20, 100, 1), EMA2_range=(20, 100, 1), periods_range=(5, 20, 1), rsi_upper_range=(65, 80, 1),rsi_lower_range=(20, 35, 1), metric="Multiple", n_trials=1000, mode="macd_rsi_combined")

[I 2025-07-29 20:54:16,728] A new study created in memory with name: no-name-515383b4-faec-4110-a1e7-92a5f886fb66
[I 2025-07-29 20:54:16,823] Trial 0 finished with value: -0.42620743968362784 and parameters: {'EMA_S': 51, 'EMA_L': 75, 'signal_mw': 13, 'RSI_periods': 5, 'RSI_upper': 68, 'RSI_lower': 34}. Best is trial 0 with value: -0.42620743968362784.
[I 2025-07-29 20:54:16,930] Trial 1 finished with value: -0.43557315541408675 and parameters: {'EMA_S': 52, 'EMA_L': 24, 'signal_mw': 14, 'RSI_periods': 16, 'RSI_upper': 70, 'RSI_lower': 24}. Best is trial 1 with value: -0.43557315541408675.
[I 2025-07-29 20:54:17,122] Trial 2 finished with value: -0.4683183695086263 and parameters: {'EMA_S': 52, 'EMA_L': 43, 'signal_mw': 15, 'RSI_periods': 16, 'RSI_upper': 77, 'RSI_lower': 32}. Best is trial 2 with value: -0.4683183695086263.
[I 2025-07-29 20:54:17,224] Trial 3 finished with value: -0.8733682048154701 and parameters: {'EMA_S': 35, 'EMA_L': 99, 'signal_mw': 5, 'RSI_periods': 11, 'RSI_upper': 79, 'RSI_lower': 32}. Best is trial 3 with value: -0.8733682048154701.
[I 2025-07-29 20:54:17,313] Trial 4 finished with value: -0.46489377229555495 and parameters: {'EMA_S': 88, 'EMA_L': 84, 'signal_mw': 12, 'RSI_periods': 9, 'RSI_upper': 74, 'RSI_lower': 28}. Best is trial 3 with value: -0.8733682048154701.
[I 2025-07-29 20:54:17,400] Trial 5 finished with value: -0.46322027827493983 and parameters: {'EMA_S': 22, 'EMA_L': 22, 'signal_mw': 16, 'RSI_periods': 7, 'RSI_upper': 69, 'RSI_lower': 30}. Best is trial 3 with value: -0.8733682048154701.
[I 2025-07-29 20:54:17,473] Trial 6 finished with value: -0.36704166695705037 and parameters: {'EMA_S': 65, 'EMA_L': 24, 'signal_mw': 16, 'RSI_periods': 13, 'RSI_upper': 67, 'RSI_lower': 32}. Best is trial 3 with value: -0.8733682048154701.
[I 2025-07-29 20:54:17,539] Trial 7 finished with value: -0.4615618634398267 and parameters: {'EMA_S': 82, 'EMA_L': 61, 'signal_mw': 15, 'RSI_periods': 12, 'RSI_upper': 68, 'RSI_lower': 33}. Best is trial 3 with value: -0.8733682048154701.
[I 2025-07-29 20:54:17,610] Trial 8 finished with value: -0.8611528958354137 and parameters: {'EMA_S': 61, 'EMA_L': 82, 'signal_mw': 18, 'RSI_periods': 11, 'RSI_upper': 78, 'RSI_lower': 29}. Best is trial 3 with value: -0.8733682048154701.
[I 2025-07-29 20:54:17,687] Trial 9 finished with value: -0.7095829061994204 and parameters: {'EMA_S': 34, 'EMA_L': 64, 'signal_mw': 17, 'RSI_periods': 9, 'RSI_upper': 70, 'RSI_lower': 28}. Best is trial 3 with value: -0.8733682048154701.
[I 2025-07-29 20:54:17,790] Trial 10 finished with value: -0.998294848877829 and parameters: {'EMA_S': 33, 'EMA_L': 98, 'signal_mw': 5, 'RSI_periods': 19, 'RSI_upper': 74, 'RSI_lower': 20}. Best is trial 10 with value: -0.998294848877829.
[I 2025-07-29 20:54:17,887] Trial 11 finished with value: -1.001345933514996 and parameters: {'EMA_S': 33, 'EMA_L': 98, 'signal_mw': 5, 'RSI_periods': 19, 'RSI_upper': 74, 'RSI_lower': 21}. Best is trial 11 with value: -1.001345933514996.
[I 2025-07-29 20:54:17,994] Trial 12 finished with value: -0.9977940127397632 and parameters: {'EMA_S': 21, 'EMA_L': 90, 'signal_mw': 5, 'RSI_periods': 19, 'RSI_upper': 74, 'RSI_lower': 20}. Best is trial 11 with value: -1.001345933514996.
[I 2025-07-29 20:54:18,092] Trial 13 finished with value: -1.002449024671961 and parameters: {'EMA_S': 36, 'EMA_L': 99, 'signal_mw': 8, 'RSI_periods': 19, 'RSI_upper': 74, 'RSI_lower': 20}. Best is trial 13 with value: -1.002449024671961.
[I 2025-07-29 20:54:18,193] Trial 14 finished with value: -0.9817250202042533 and parameters: {'EMA_S': 39, 'EMA_L': 75, 'signal_mw': 9, 'RSI_periods': 16, 'RSI_upper': 72, 'RSI_lower': 23}. Best is trial 13 with value: -1.002449024671961.
[I 2025-07-29 20:54:18,308] Trial 15 finished with value: -1.0176095174531943 and parameters: {'EMA_S': 43, 'EMA_L': 46, 'signal_mw': 8, 'RSI_periods': 18, 'RSI_upper': 76, 'RSI_lower': 23}. Best is trial 15 with value: -1.0176095174531943.
[I 2025-07-29 20:54:18,414] Trial 16 finished with value: -0.3326266488173184 and parameters: {'EMA_S': 74, 'EMA_L': 45, 'signal_mw': 9, 'RSI_periods': 14, 'RSI_upper': 65, 'RSI_lower': 25}. Best is trial 15 with value: -1.0176095174531943.
[I 2025-07-29 20:54:18,513] Trial 17 finished with value: -1.0317406546094905 and parameters: {'EMA_S': 45, 'EMA_L': 46, 'signal_mw': 9, 'RSI_periods': 17, 'RSI_upper': 76, 'RSI_lower': 22}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:18,614] Trial 18 finished with value: -0.44907779311039975 and parameters: {'EMA_S': 45, 'EMA_L': 43, 'signal_mw': 11, 'RSI_periods': 15, 'RSI_upper': 76, 'RSI_lower': 26}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:18,730] Trial 19 finished with value: -0.5046004414849969 and parameters: {'EMA_S': 67, 'EMA_L': 52, 'signal_mw': 7, 'RSI_periods': 17, 'RSI_upper': 76, 'RSI_lower': 22}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:18,840] Trial 20 finished with value: -0.45074487515450307 and parameters: {'EMA_S': 45, 'EMA_L': 31, 'signal_mw': 11, 'RSI_periods': 17, 'RSI_upper': 72, 'RSI_lower': 23}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:18,937] Trial 21 finished with value: -1.0157740945227816 and parameters: {'EMA_S': 43, 'EMA_L': 53, 'signal_mw': 8, 'RSI_periods': 18, 'RSI_upper': 76, 'RSI_lower': 22}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:19,077] Trial 22 finished with value: -1.031526362291349 and parameters: {'EMA_S': 47, 'EMA_L': 53, 'signal_mw': 7, 'RSI_periods': 17, 'RSI_upper': 76, 'RSI_lower': 22}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:19,237] Trial 23 finished with value: -0.5490582714149298 and parameters: {'EMA_S': 98, 'EMA_L': 36, 'signal_mw': 7, 'RSI_periods': 14, 'RSI_upper': 79, 'RSI_lower': 25}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:19,337] Trial 24 finished with value: -0.5742961565254158 and parameters: {'EMA_S': 56, 'EMA_L': 52, 'signal_mw': 10, 'RSI_periods': 18, 'RSI_upper': 77, 'RSI_lower': 22}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:19,447] Trial 25 finished with value: -1.0012437901591125 and parameters: {'EMA_S': 28, 'EMA_L': 68, 'signal_mw': 7, 'RSI_periods': 17, 'RSI_upper': 75, 'RSI_lower': 24}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:19,537] Trial 26 finished with value: -0.4880983869961067 and parameters: {'EMA_S': 43, 'EMA_L': 35, 'signal_mw': 20, 'RSI_periods': 15, 'RSI_upper': 78, 'RSI_lower': 26}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:19,646] Trial 27 finished with value: -0.5633401520623946 and parameters: {'EMA_S': 59, 'EMA_L': 56, 'signal_mw': 10, 'RSI_periods': 18, 'RSI_upper': 72, 'RSI_lower': 21}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:19,747] Trial 28 finished with value: -0.5008055634372732 and parameters: {'EMA_S': 50, 'EMA_L': 47, 'signal_mw': 6, 'RSI_periods': 15, 'RSI_upper': 77, 'RSI_lower': 23}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:19,857] Trial 29 finished with value: -0.6314604282217078 and parameters: {'EMA_S': 49, 'EMA_L': 68, 'signal_mw': 13, 'RSI_periods': 5, 'RSI_upper': 75, 'RSI_lower': 24}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:19,960] Trial 30 finished with value: -0.9901850813428638 and parameters: {'EMA_S': 27, 'EMA_L': 37, 'signal_mw': 9, 'RSI_periods': 13, 'RSI_upper': 73, 'RSI_lower': 21}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:20,083] Trial 31 finished with value: -1.0157612087103807 and parameters: {'EMA_S': 41, 'EMA_L': 53, 'signal_mw': 8, 'RSI_periods': 18, 'RSI_upper': 76, 'RSI_lower': 22}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:20,186] Trial 32 finished with value: -1.0191250951476476 and parameters: {'EMA_S': 48, 'EMA_L': 58, 'signal_mw': 8, 'RSI_periods': 17, 'RSI_upper': 78, 'RSI_lower': 22}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:20,284] Trial 33 finished with value: -1.0031411129102534 and parameters: {'EMA_S': 55, 'EMA_L': 59, 'signal_mw': 6, 'RSI_periods': 17, 'RSI_upper': 78, 'RSI_lower': 25}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:20,374] Trial 34 finished with value: -0.5402033874288305 and parameters: {'EMA_S': 51, 'EMA_L': 48, 'signal_mw': 10, 'RSI_periods': 16, 'RSI_upper': 79, 'RSI_lower': 23}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:20,482] Trial 35 finished with value: -0.5024199915460263 and parameters: {'EMA_S': 47, 'EMA_L': 40, 'signal_mw': 12, 'RSI_periods': 16, 'RSI_upper': 77, 'RSI_lower': 24}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:20,574] Trial 36 finished with value: -0.5089056247514958 and parameters: {'EMA_S': 55, 'EMA_L': 31, 'signal_mw': 6, 'RSI_periods': 17, 'RSI_upper': 75, 'RSI_lower': 21}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:20,677] Trial 37 finished with value: -0.9991424657212223 and parameters: {'EMA_S': 39, 'EMA_L': 66, 'signal_mw': 8, 'RSI_periods': 14, 'RSI_upper': 78, 'RSI_lower': 26}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:20,783] Trial 38 finished with value: -0.9583104765793923 and parameters: {'EMA_S': 65, 'EMA_L': 73, 'signal_mw': 11, 'RSI_periods': 15, 'RSI_upper': 77, 'RSI_lower': 22}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:20,888] Trial 39 finished with value: -0.9886121144084133 and parameters: {'EMA_S': 28, 'EMA_L': 58, 'signal_mw': 7, 'RSI_periods': 16, 'RSI_upper': 71, 'RSI_lower': 24}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:21,005] Trial 40 finished with value: -0.5324152810592028 and parameters: {'EMA_S': 61, 'EMA_L': 49, 'signal_mw': 14, 'RSI_periods': 9, 'RSI_upper': 79, 'RSI_lower': 27}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:21,093] Trial 41 finished with value: -1.016034444744752 and parameters: {'EMA_S': 42, 'EMA_L': 55, 'signal_mw': 8, 'RSI_periods': 18, 'RSI_upper': 76, 'RSI_lower': 22}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:21,189] Trial 42 finished with value: -1.0043296285412104 and parameters: {'EMA_S': 48, 'EMA_L': 62, 'signal_mw': 8, 'RSI_periods': 18, 'RSI_upper': 75, 'RSI_lower': 21}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:21,289] Trial 43 finished with value: -0.9951726709541974 and parameters: {'EMA_S': 38, 'EMA_L': 41, 'signal_mw': 6, 'RSI_periods': 19, 'RSI_upper': 78, 'RSI_lower': 23}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:21,390] Trial 44 finished with value: -0.989702112879648 and parameters: {'EMA_S': 53, 'EMA_L': 56, 'signal_mw': 9, 'RSI_periods': 18, 'RSI_upper': 73, 'RSI_lower': 20}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:21,553] Trial 45 finished with value: -1.0112998251083123 and parameters: {'EMA_S': 41, 'EMA_L': 48, 'signal_mw': 7, 'RSI_periods': 17, 'RSI_upper': 76, 'RSI_lower': 22}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:21,895] Trial 46 finished with value: -0.9816932239084143 and parameters: {'EMA_S': 31, 'EMA_L': 62, 'signal_mw': 10, 'RSI_periods': 16, 'RSI_upper': 77, 'RSI_lower': 30}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:22,226] Trial 47 finished with value: -1.0216859299029009 and parameters: {'EMA_S': 44, 'EMA_L': 56, 'signal_mw': 9, 'RSI_periods': 19, 'RSI_upper': 73, 'RSI_lower': 21}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:22,525] Trial 48 finished with value: -1.0018651617470746 and parameters: {'EMA_S': 36, 'EMA_L': 44, 'signal_mw': 9, 'RSI_periods': 19, 'RSI_upper': 73, 'RSI_lower': 20}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:22,807] Trial 49 finished with value: -0.9909259185666862 and parameters: {'EMA_S': 46, 'EMA_L': 50, 'signal_mw': 12, 'RSI_periods': 10, 'RSI_upper': 70, 'RSI_lower': 21}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:23,002] Trial 50 finished with value: -1.0103398545683406 and parameters: {'EMA_S': 59, 'EMA_L': 70, 'signal_mw': 5, 'RSI_periods': 19, 'RSI_upper': 75, 'RSI_lower': 23}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:23,151] Trial 51 finished with value: -1.0159575891683352 and parameters: {'EMA_S': 41, 'EMA_L': 56, 'signal_mw': 8, 'RSI_periods': 18, 'RSI_upper': 76, 'RSI_lower': 22}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:23,298] Trial 52 finished with value: -1.0058177069620524 and parameters: {'EMA_S': 52, 'EMA_L': 64, 'signal_mw': 9, 'RSI_periods': 17, 'RSI_upper': 68, 'RSI_lower': 21}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:23,401] Trial 53 finished with value: -1.0186259296220939 and parameters: {'EMA_S': 45, 'EMA_L': 55, 'signal_mw': 7, 'RSI_periods': 19, 'RSI_upper': 74, 'RSI_lower': 20}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:23,511] Trial 54 finished with value: -0.9624960701497607 and parameters: {'EMA_S': 45, 'EMA_L': 46, 'signal_mw': 6, 'RSI_periods': 19, 'RSI_upper': 74, 'RSI_lower': 34}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:23,621] Trial 55 finished with value: -1.0214464904188967 and parameters: {'EMA_S': 37, 'EMA_L': 81, 'signal_mw': 7, 'RSI_periods': 19, 'RSI_upper': 71, 'RSI_lower': 20}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:23,730] Trial 56 finished with value: -1.0136256476586951 and parameters: {'EMA_S': 32, 'EMA_L': 82, 'signal_mw': 7, 'RSI_periods': 19, 'RSI_upper': 71, 'RSI_lower': 20}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:23,888] Trial 57 finished with value: -1.0142098290740822 and parameters: {'EMA_S': 37, 'EMA_L': 89, 'signal_mw': 5, 'RSI_periods': 19, 'RSI_upper': 71, 'RSI_lower': 20}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:24,040] Trial 58 finished with value: -1.0184756760794456 and parameters: {'EMA_S': 48, 'EMA_L': 79, 'signal_mw': 7, 'RSI_periods': 17, 'RSI_upper': 73, 'RSI_lower': 20}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:24,165] Trial 59 finished with value: -1.0003607589028933 and parameters: {'EMA_S': 25, 'EMA_L': 60, 'signal_mw': 10, 'RSI_periods': 18, 'RSI_upper': 72, 'RSI_lower': 21}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:24,398] Trial 60 finished with value: -1.0108033424078353 and parameters: {'EMA_S': 35, 'EMA_L': 65, 'signal_mw': 6, 'RSI_periods': 19, 'RSI_upper': 69, 'RSI_lower': 20}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:24,556] Trial 61 finished with value: -1.0161666718860376 and parameters: {'EMA_S': 48, 'EMA_L': 85, 'signal_mw': 7, 'RSI_periods': 17, 'RSI_upper': 73, 'RSI_lower': 20}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:24,689] Trial 62 finished with value: -0.9762783567402239 and parameters: {'EMA_S': 45, 'EMA_L': 77, 'signal_mw': 7, 'RSI_periods': 15, 'RSI_upper': 74, 'RSI_lower': 21}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:24,800] Trial 63 finished with value: -0.9809562743191479 and parameters: {'EMA_S': 39, 'EMA_L': 78, 'signal_mw': 9, 'RSI_periods': 16, 'RSI_upper': 73, 'RSI_lower': 20}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:24,942] Trial 64 finished with value: -1.0167823056418743 and parameters: {'EMA_S': 56, 'EMA_L': 71, 'signal_mw': 8, 'RSI_periods': 17, 'RSI_upper': 72, 'RSI_lower': 21}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:25,090] Trial 65 finished with value: -1.0004355542162047 and parameters: {'EMA_S': 50, 'EMA_L': 91, 'signal_mw': 6, 'RSI_periods': 18, 'RSI_upper': 70, 'RSI_lower': 22}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:25,298] Trial 66 finished with value: -0.6208561176608779 and parameters: {'EMA_S': 53, 'EMA_L': 52, 'signal_mw': 7, 'RSI_periods': 12, 'RSI_upper': 71, 'RSI_lower': 20}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:25,490] Trial 67 finished with value: -0.4644612573194649 and parameters: {'EMA_S': 75, 'EMA_L': 58, 'signal_mw': 11, 'RSI_periods': 17, 'RSI_upper': 66, 'RSI_lower': 21}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:25,620] Trial 68 finished with value: -0.6239213982978696 and parameters: {'EMA_S': 31, 'EMA_L': 92, 'signal_mw': 9, 'RSI_periods': 7, 'RSI_upper': 75, 'RSI_lower': 31}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:25,753] Trial 69 finished with value: -0.9827893428060716 and parameters: {'EMA_S': 43, 'EMA_L': 82, 'signal_mw': 8, 'RSI_periods': 18, 'RSI_upper': 74, 'RSI_lower': 22}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:25,892] Trial 70 finished with value: -0.9691225862875564 and parameters: {'EMA_S': 48, 'EMA_L': 54, 'signal_mw': 5, 'RSI_periods': 16, 'RSI_upper': 74, 'RSI_lower': 23}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:26,105] Trial 71 finished with value: -1.0259234912631465 and parameters: {'EMA_S': 45, 'EMA_L': 50, 'signal_mw': 8, 'RSI_periods': 19, 'RSI_upper': 73, 'RSI_lower': 21}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:26,250] Trial 72 finished with value: -1.0311931073874043 and parameters: {'EMA_S': 45, 'EMA_L': 51, 'signal_mw': 7, 'RSI_periods': 19, 'RSI_upper': 73, 'RSI_lower': 21}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:26,359] Trial 73 finished with value: -1.02833444799792 and parameters: {'EMA_S': 40, 'EMA_L': 50, 'signal_mw': 8, 'RSI_periods': 19, 'RSI_upper': 72, 'RSI_lower': 21}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:26,471] Trial 74 finished with value: -0.998663683807747 and parameters: {'EMA_S': 34, 'EMA_L': 42, 'signal_mw': 8, 'RSI_periods': 19, 'RSI_upper': 72, 'RSI_lower': 22}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:26,576] Trial 75 finished with value: -0.6720127950797203 and parameters: {'EMA_S': 39, 'EMA_L': 39, 'signal_mw': 10, 'RSI_periods': 18, 'RSI_upper': 69, 'RSI_lower': 21}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:26,689] Trial 76 finished with value: -1.0286688637772585 and parameters: {'EMA_S': 42, 'EMA_L': 51, 'signal_mw': 9, 'RSI_periods': 19, 'RSI_upper': 71, 'RSI_lower': 22}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:26,790] Trial 77 finished with value: -1.030802194351419 and parameters: {'EMA_S': 41, 'EMA_L': 50, 'signal_mw': 9, 'RSI_periods': 19, 'RSI_upper': 71, 'RSI_lower': 23}. Best is trial 17 with value: -1.0317406546094905.
[I 2025-07-29 20:54:26,904] Trial 78 finished with value: -1.0325965720867065 and parameters: {'EMA_S': 43, 'EMA_L': 49, 'signal_mw': 9, 'RSI_periods': 19, 'RSI_upper': 72, 'RSI_lower': 24}. Best is trial 78 with value: -1.0325965720867065.
[I 2025-07-29 20:54:27,054] Trial 79 finished with value: -0.9934527252174313 and parameters: {'EMA_S': 41, 'EMA_L': 51, 'signal_mw': 10, 'RSI_periods': 18, 'RSI_upper': 70, 'RSI_lower': 25}. Best is trial 78 with value: -1.0325965720867065.
[I 2025-07-29 20:54:27,191] Trial 80 finished with value: -1.0107430863525122 and parameters: {'EMA_S': 41, 'EMA_L': 45, 'signal_mw': 9, 'RSI_periods': 18, 'RSI_upper': 72, 'RSI_lower': 24}. Best is trial 78 with value: -1.0325965720867065.
[I 2025-07-29 20:54:27,307] Trial 81 finished with value: -1.0117517220449328 and parameters: {'EMA_S': 43, 'EMA_L': 50, 'signal_mw': 11, 'RSI_periods': 19, 'RSI_upper': 71, 'RSI_lower': 23}. Best is trial 78 with value: -1.0325965720867065.

Optuna optimization completed.
Best Parameters (MACD + RSI Combination): EMA_S = 31, EMA_L = 68, RSI_periods = 12, RSI_upper = 69, RSI_lower = 21, signal_mw = 9
Best Multiple: 1.216121
====================================================================================================
MACD + RSI COMBINATION STRATEGY | INSTRUMENT = GBP_USD
----------------------------------------------------------------------------------------------------
PERFORMANCE MEASURES:


Multiple (Strategy):         1.216121
Multiple (Buy-and-Hold):     1.181254
--------------------------------------
Out-/Underperformance:       0.034867


CAGR:                        0.01245
Annualized Mean:             0.012417
Annualized Std:              0.025148
Sharpe Ratio:                0.493775
Sortino Ratio:               1.597966
Maximum Drawdown:            0.021857
Calmar Ratio:                0.569622
Max Drawdown Duration:       1293 Days
Kelly Criterion:             18.861536
====================================================================================================

In [18]:
tester.add_leverage(9)

====================================================================================================
EMA/SMA + RSI COMBINED STRATEGY | INSTRUMENT = GBP_USD
----------------------------------------------------------------------------------------------------
PERFORMANCE MEASURES:


Multiple (Strategy):         4.296234
Multiple (Buy-and-Hold):     1.181254
--------------------------------------
Out-/Underperformance:       3.11498


CAGR:                        0.096564
Annualized Mean:             0.092512
Annualized Std:              0.183793
Sharpe Ratio:                0.503347
Sortino Ratio:               1.303172
Maximum Drawdown:            0.185066
Calmar Ratio:                0.521778
Max Drawdown Duration:       1293 Days
Kelly Criterion:             2.181646
====================================================================================================

3. Testing EMA

In [19]:
tester.optimize_parameters_optuna(EMA1_range=(20, 100, 1), EMA2_range=(20, 100, 1), periods_range=(5, 20, 1), rsi_upper_range=(65, 80, 1),rsi_lower_range=(20, 35, 1), metric="Multiple", n_trials=1000, mode="ema")

[I 2025-07-29 20:57:21,435] A new study created in memory with name: no-name-b8db13aa-dda8-4f0f-b00d-99d91e19a2b9
[I 2025-07-29 20:57:21,522] Trial 0 finished with value: -0.37818593313984433 and parameters: {'EMA_S': 47, 'EMA_L': 20}. Best is trial 0 with value: -0.37818593313984433.
[I 2025-07-29 20:57:21,610] Trial 1 finished with value: -1.2729302060331917 and parameters: {'EMA_S': 31, 'EMA_L': 65}. Best is trial 1 with value: -1.2729302060331917.
[I 2025-07-29 20:57:21,702] Trial 2 finished with value: -0.4131710401312 and parameters: {'EMA_S': 52, 'EMA_L': 31}. Best is trial 1 with value: -1.2729302060331917.
[I 2025-07-29 20:57:21,844] Trial 3 finished with value: -1.0126149760032843 and parameters: {'EMA_S': 30, 'EMA_L': 76}. Best is trial 1 with value: -1.2729302060331917.
[I 2025-07-29 20:57:21,953] Trial 4 finished with value: -0.9396584830150577 and parameters: {'EMA_S': 73, 'EMA_L': 76}. Best is trial 1 with value: -1.2729302060331917.
[I 2025-07-29 20:57:22,026] Trial 5 finished with value: -0.9723612725784994 and parameters: {'EMA_S': 94, 'EMA_L': 79}. Best is trial 1 with value: -1.2729302060331917.
[I 2025-07-29 20:57:22,086] Trial 6 finished with value: -0.7164767643010674 and parameters: {'EMA_S': 84, 'EMA_L': 28}. Best is trial 1 with value: -1.2729302060331917.
[I 2025-07-29 20:57:22,142] Trial 7 finished with value: -0.84655798576651 and parameters: {'EMA_S': 76, 'EMA_L': 76}. Best is trial 1 with value: -1.2729302060331917.
[I 2025-07-29 20:57:22,202] Trial 8 finished with value: -1.06690458365207 and parameters: {'EMA_S': 22, 'EMA_L': 99}. Best is trial 1 with value: -1.2729302060331917.
[I 2025-07-29 20:57:22,259] Trial 9 finished with value: -0.9446346306554756 and parameters: {'EMA_S': 72, 'EMA_L': 82}. Best is trial 1 with value: -1.2729302060331917.
[I 2025-07-29 20:57:22,350] Trial 10 finished with value: -1.4969717829575555 and parameters: {'EMA_S': 37, 'EMA_L': 51}. Best is trial 10 with value: -1.4969717829575555.
[I 2025-07-29 20:57:22,450] Trial 11 finished with value: -1.5065064826292873 and parameters: {'EMA_S': 38, 'EMA_L': 50}. Best is trial 11 with value: -1.5065064826292873.
[I 2025-07-29 20:57:22,560] Trial 12 finished with value: -1.550085448733282 and parameters: {'EMA_S': 41, 'EMA_L': 43}. Best is trial 12 with value: -1.550085448733282.
[I 2025-07-29 20:57:22,668] Trial 13 finished with value: -0.6529948871762561 and parameters: {'EMA_S': 48, 'EMA_L': 47}. Best is trial 12 with value: -1.550085448733282.
[I 2025-07-29 20:57:22,764] Trial 14 finished with value: -0.7759898876790423 and parameters: {'EMA_S': 61, 'EMA_L': 42}. Best is trial 12 with value: -1.550085448733282.
[I 2025-07-29 20:57:22,845] Trial 15 finished with value: -1.052560877650332 and parameters: {'EMA_S': 37, 'EMA_L': 59}. Best is trial 12 with value: -1.550085448733282.
[I 2025-07-29 20:57:22,919] Trial 16 finished with value: -0.7013367271841271 and parameters: {'EMA_S': 60, 'EMA_L': 38}. Best is trial 12 with value: -1.550085448733282.
[I 2025-07-29 20:57:22,989] Trial 17 finished with value: -1.5553568198195125 and parameters: {'EMA_S': 21, 'EMA_L': 57}. Best is trial 17 with value: -1.5553568198195125.
[I 2025-07-29 20:57:23,055] Trial 18 finished with value: -1.4487640655564389 and parameters: {'EMA_S': 23, 'EMA_L': 62}. Best is trial 17 with value: -1.5553568198195125.
[I 2025-07-29 20:57:23,124] Trial 19 finished with value: -1.5495519762055403 and parameters: {'EMA_S': 27, 'EMA_L': 56}. Best is trial 17 with value: -1.5553568198195125.
[I 2025-07-29 20:57:23,193] Trial 20 finished with value: -0.7700425565925877 and parameters: {'EMA_S': 43, 'EMA_L': 67}. Best is trial 17 with value: -1.5553568198195125.
[I 2025-07-29 20:57:23,272] Trial 21 finished with value: -1.3875998053576977 and parameters: {'EMA_S': 20, 'EMA_L': 56}. Best is trial 17 with value: -1.5553568198195125.
[I 2025-07-29 20:57:23,347] Trial 22 finished with value: -1.342504680138597 and parameters: {'EMA_S': 29, 'EMA_L': 40}. Best is trial 17 with value: -1.5553568198195125.
[I 2025-07-29 20:57:23,417] Trial 23 finished with value: -1.5667305193282415 and parameters: {'EMA_S': 26, 'EMA_L': 54}. Best is trial 23 with value: -1.5667305193282415.
[I 2025-07-29 20:57:23,514] Trial 24 finished with value: -1.3779600243882657 and parameters: {'EMA_S': 34, 'EMA_L': 35}. Best is trial 23 with value: -1.5667305193282415.
[I 2025-07-29 20:57:23,599] Trial 25 finished with value: -1.3266293366603734 and parameters: {'EMA_S': 42, 'EMA_L': 49}. Best is trial 23 with value: -1.5667305193282415.
[I 2025-07-29 20:57:23,672] Trial 26 finished with value: -0.6444505844540276 and parameters: {'EMA_S': 54, 'EMA_L': 43}. Best is trial 23 with value: -1.5667305193282415.
[I 2025-07-29 20:57:23,749] Trial 27 finished with value: -1.1959284062985576 and parameters: {'EMA_S': 25, 'EMA_L': 70}. Best is trial 23 with value: -1.5667305193282415.
[I 2025-07-29 20:57:23,824] Trial 28 finished with value: -0.7517930720689204 and parameters: {'EMA_S': 42, 'EMA_L': 91}. Best is trial 23 with value: -1.5667305193282415.
[I 2025-07-29 20:57:23,889] Trial 29 finished with value: -0.3669064577996363 and parameters: {'EMA_S': 33, 'EMA_L': 25}. Best is trial 23 with value: -1.5667305193282415.
[I 2025-07-29 20:57:23,953] Trial 30 finished with value: -1.3410306374701084 and parameters: {'EMA_S': 20, 'EMA_L': 55}. Best is trial 23 with value: -1.5667305193282415.
[I 2025-07-29 20:57:24,014] Trial 31 finished with value: -1.5361890115192474 and parameters: {'EMA_S': 26, 'EMA_L': 55}. Best is trial 23 with value: -1.5667305193282415.
[I 2025-07-29 20:57:24,081] Trial 32 finished with value: -1.3594404568644507 and parameters: {'EMA_S': 28, 'EMA_L': 61}. Best is trial 23 with value: -1.5667305193282415.
[I 2025-07-29 20:57:24,140] Trial 33 finished with value: -1.5405070593880852 and parameters: {'EMA_S': 32, 'EMA_L': 46}. Best is trial 23 with value: -1.5667305193282415.
[I 2025-07-29 20:57:24,197] Trial 34 finished with value: -1.2633278999045179 and parameters: {'EMA_S': 26, 'EMA_L': 67}. Best is trial 23 with value: -1.5667305193282415.
[I 2025-07-29 20:57:24,265] Trial 35 finished with value: -0.4590815967450118 and parameters: {'EMA_S': 49, 'EMA_L': 35}. Best is trial 23 with value: -1.5667305193282415.
[I 2025-07-29 20:57:24,331] Trial 36 finished with value: -1.4421324576369456 and parameters: {'EMA_S': 34, 'EMA_L': 53}. Best is trial 23 with value: -1.5667305193282415.
[I 2025-07-29 20:57:24,407] Trial 37 finished with value: -0.7479663011793152 and parameters: {'EMA_S': 54, 'EMA_L': 71}. Best is trial 23 with value: -1.5667305193282415.
[I 2025-07-29 20:57:24,474] Trial 38 finished with value: -1.3355311733866146 and parameters: {'EMA_S': 30, 'EMA_L': 60}. Best is trial 23 with value: -1.5667305193282415.
[I 2025-07-29 20:57:24,540] Trial 39 finished with value: -1.43708422978782 and parameters: {'EMA_S': 44, 'EMA_L': 45}. Best is trial 23 with value: -1.5667305193282415.
[I 2025-07-29 20:57:24,628] Trial 40 finished with value: -0.8489406902298582 and parameters: {'EMA_S': 95, 'EMA_L': 64}. Best is trial 23 with value: -1.5667305193282415.
[I 2025-07-29 20:57:24,708] Trial 41 finished with value: -1.412718135330767 and parameters: {'EMA_S': 32, 'EMA_L': 57}. Best is trial 23 with value: -1.5667305193282415.
[I 2025-07-29 20:57:24,786] Trial 42 finished with value: -1.4508170516447674 and parameters: {'EMA_S': 23, 'EMA_L': 46}. Best is trial 23 with value: -1.5667305193282415.
[I 2025-07-29 20:57:24,840] Trial 43 finished with value: -1.544496700213196 and parameters: {'EMA_S': 29, 'EMA_L': 52}. Best is trial 23 with value: -1.5667305193282415.
[I 2025-07-29 20:57:24,897] Trial 44 finished with value: -1.3942620866023305 and parameters: {'EMA_S': 38, 'EMA_L': 53}. Best is trial 23 with value: -1.5667305193282415.
[I 2025-07-29 20:57:24,964] Trial 45 finished with value: -0.475326321838384 and parameters: {'EMA_S': 66, 'EMA_L': 20}. Best is trial 23 with value: -1.5667305193282415.
[I 2025-07-29 20:57:25,024] Trial 46 finished with value: -0.8774819581827589 and parameters: {'EMA_S': 88, 'EMA_L': 50}. Best is trial 23 with value: -1.5667305193282415.
[I 2025-07-29 20:57:25,091] Trial 47 finished with value: -1.4959932410580894 and parameters: {'EMA_S': 27, 'EMA_L': 37}. Best is trial 23 with value: -1.5667305193282415.
[I 2025-07-29 20:57:25,158] Trial 48 finished with value: -1.2922594218032768 and parameters: {'EMA_S': 20, 'EMA_L': 32}. Best is trial 23 with value: -1.5667305193282415.
[I 2025-07-29 20:57:25,224] Trial 49 finished with value: -1.7181502165955869 and parameters: {'EMA_S': 38, 'EMA_L': 42}. Best is trial 49 with value: -1.7181502165955869.
[I 2025-07-29 20:57:25,316] Trial 50 finished with value: -1.7181502165955869 and parameters: {'EMA_S': 38, 'EMA_L': 42}. Best is trial 49 with value: -1.7181502165955869.
[I 2025-07-29 20:57:25,424] Trial 51 finished with value: -1.6767939037452477 and parameters: {'EMA_S': 37, 'EMA_L': 42}. Best is trial 49 with value: -1.7181502165955869.
[I 2025-07-29 20:57:25,532] Trial 52 finished with value: -1.6822601175618586 and parameters: {'EMA_S': 39, 'EMA_L': 40}. Best is trial 49 with value: -1.7181502165955869.
[I 2025-07-29 20:57:25,644] Trial 53 finished with value: -0.4227244570938836 and parameters: {'EMA_S': 37, 'EMA_L': 29}. Best is trial 49 with value: -1.7181502165955869.
[I 2025-07-29 20:57:25,753] Trial 54 finished with value: -0.46750253685519755 and parameters: {'EMA_S': 45, 'EMA_L': 41}. Best is trial 49 with value: -1.7181502165955869.
[I 2025-07-29 20:57:25,868] Trial 55 finished with value: -0.3917786772962622 and parameters: {'EMA_S': 40, 'EMA_L': 39}. Best is trial 49 with value: -1.7181502165955869.
[I 2025-07-29 20:57:26,108] Trial 56 finished with value: -0.45983481624561556 and parameters: {'EMA_S': 50, 'EMA_L': 33}. Best is trial 49 with value: -1.7181502165955869.
[I 2025-07-29 20:57:26,202] Trial 57 finished with value: -1.4558753197013754 and parameters: {'EMA_S': 35, 'EMA_L': 49}. Best is trial 49 with value: -1.7181502165955869.
[I 2025-07-29 20:57:26,288] Trial 58 finished with value: -1.5359842425676444 and parameters: {'EMA_S': 39, 'EMA_L': 42}. Best is trial 49 with value: -1.7181502165955869.
[I 2025-07-29 20:57:26,379] Trial 59 finished with value: -0.4560090394093785 and parameters: {'EMA_S': 47, 'EMA_L': 27}. Best is trial 49 with value: -1.7181502165955869.
[I 2025-07-29 20:57:26,453] Trial 60 finished with value: -1.7405452191273518 and parameters: {'EMA_S': 23, 'EMA_L': 37}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:26,553] Trial 61 finished with value: -1.6275894446584425 and parameters: {'EMA_S': 23, 'EMA_L': 36}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:26,690] Trial 62 finished with value: -1.725879586979475 and parameters: {'EMA_S': 24, 'EMA_L': 36}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:26,816] Trial 63 finished with value: -1.5211925109836246 and parameters: {'EMA_S': 24, 'EMA_L': 37}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:26,923] Trial 64 finished with value: -0.4234348912591396 and parameters: {'EMA_S': 35, 'EMA_L': 30}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:27,012] Trial 65 finished with value: -0.9793761487991179 and parameters: {'EMA_S': 23, 'EMA_L': 24}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:27,091] Trial 66 finished with value: -1.5116177331040739 and parameters: {'EMA_S': 30, 'EMA_L': 34}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:27,169] Trial 67 finished with value: -0.46507539310716556 and parameters: {'EMA_S': 46, 'EMA_L': 39}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:27,268] Trial 68 finished with value: -1.038958344203413 and parameters: {'EMA_S': 78, 'EMA_L': 36}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:27,349] Trial 69 finished with value: -0.9336188035106303 and parameters: {'EMA_S': 58, 'EMA_L': 45}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:27,419] Trial 70 finished with value: -0.4617558434921187 and parameters: {'EMA_S': 41, 'EMA_L': 31}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:27,503] Trial 71 finished with value: -1.4179892348956882 and parameters: {'EMA_S': 25, 'EMA_L': 41}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:27,597] Trial 72 finished with value: -0.879502768786972 and parameters: {'EMA_S': 99, 'EMA_L': 44}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:27,701] Trial 73 finished with value: -1.4022592118726411 and parameters: {'EMA_S': 30, 'EMA_L': 47}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:27,811] Trial 74 finished with value: -1.4637695291256332 and parameters: {'EMA_S': 27, 'EMA_L': 40}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:27,920] Trial 75 finished with value: -1.3837249141325532 and parameters: {'EMA_S': 22, 'EMA_L': 34}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:28,003] Trial 76 finished with value: -1.6839858689990086 and parameters: {'EMA_S': 32, 'EMA_L': 48}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:28,107] Trial 77 finished with value: -1.6839858689990086 and parameters: {'EMA_S': 32, 'EMA_L': 48}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:28,211] Trial 78 finished with value: -1.4713446010415574 and parameters: {'EMA_S': 36, 'EMA_L': 48}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:28,317] Trial 79 finished with value: -1.3704306439259146 and parameters: {'EMA_S': 32, 'EMA_L': 39}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:28,416] Trial 80 finished with value: -1.4360484152320505 and parameters: {'EMA_S': 39, 'EMA_L': 44}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:28,515] Trial 81 finished with value: -1.4185502874733975 and parameters: {'EMA_S': 33, 'EMA_L': 42}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:28,610] Trial 82 finished with value: -0.43944002304215285 and parameters: {'EMA_S': 43, 'EMA_L': 38}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:28,698] Trial 83 finished with value: -1.4419652617859449 and parameters: {'EMA_S': 31, 'EMA_L': 36}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:28,782] Trial 84 finished with value: -1.3409146838053634 and parameters: {'EMA_S': 28, 'EMA_L': 43}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:28,855] Trial 85 finished with value: -1.434658012148301 and parameters: {'EMA_S': 36, 'EMA_L': 51}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:28,933] Trial 86 finished with value: -1.2564858707706905 and parameters: {'EMA_S': 22, 'EMA_L': 32}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:29,005] Trial 87 finished with value: -1.305334780159348 and parameters: {'EMA_S': 25, 'EMA_L': 47}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:29,106] Trial 88 finished with value: -0.40732287567083186 and parameters: {'EMA_S': 38, 'EMA_L': 26}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:29,200] Trial 89 finished with value: -0.7741889746880899 and parameters: {'EMA_S': 34, 'EMA_L': 88}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:29,298] Trial 90 finished with value: -1.3576990259815898 and parameters: {'EMA_S': 29, 'EMA_L': 41}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:29,377] Trial 91 finished with value: -1.4996072556560858 and parameters: {'EMA_S': 20, 'EMA_L': 49}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:29,447] Trial 92 finished with value: -1.5447602631810473 and parameters: {'EMA_S': 27, 'EMA_L': 54}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:29,508] Trial 93 finished with value: -1.3114862665031037 and parameters: {'EMA_S': 24, 'EMA_L': 51}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:29,574] Trial 94 finished with value: -1.5405070593880852 and parameters: {'EMA_S': 32, 'EMA_L': 46}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:29,657] Trial 95 finished with value: -1.0681102644718272 and parameters: {'EMA_S': 41, 'EMA_L': 57}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:29,739] Trial 96 finished with value: -1.4464661367628548 and parameters: {'EMA_S': 26, 'EMA_L': 37}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:29,820] Trial 97 finished with value: -1.5139628055573446 and parameters: {'EMA_S': 22, 'EMA_L': 43}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:29,908] Trial 98 finished with value: -1.5079943580456598 and parameters: {'EMA_S': 29, 'EMA_L': 35}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:29,981] Trial 99 finished with value: -1.4410152672417773 and parameters: {'EMA_S': 32, 'EMA_L': 45}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:30,048] Trial 100 finished with value: -1.3856515951274606 and parameters: {'EMA_S': 35, 'EMA_L': 39}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:30,115] Trial 101 finished with value: -1.486972317099213 and parameters: {'EMA_S': 21, 'EMA_L': 62}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:30,181] Trial 102 finished with value: -1.3730245251877624 and parameters: {'EMA_S': 24, 'EMA_L': 53}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:30,264] Trial 103 finished with value: -1.5551707473007825 and parameters: {'EMA_S': 26, 'EMA_L': 56}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:30,333] Trial 104 finished with value: -1.2321411208760729 and parameters: {'EMA_S': 28, 'EMA_L': 59}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:30,399] Trial 105 finished with value: -0.9564925809381551 and parameters: {'EMA_S': 69, 'EMA_L': 49}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:30,465] Trial 106 finished with value: -1.341669337278349 and parameters: {'EMA_S': 23, 'EMA_L': 40}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:30,516] Trial 107 finished with value: -1.0688525861243516 and parameters: {'EMA_S': 20, 'EMA_L': 99}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:30,600] Trial 108 finished with value: -0.4227244570938836 and parameters: {'EMA_S': 37, 'EMA_L': 29}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:30,683] Trial 109 finished with value: -1.5231876552819874 and parameters: {'EMA_S': 31, 'EMA_L': 47}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:30,765] Trial 110 finished with value: -0.43450246102656365 and parameters: {'EMA_S': 44, 'EMA_L': 33}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:30,869] Trial 111 finished with value: -1.4536164778203005 and parameters: {'EMA_S': 25, 'EMA_L': 57}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:30,975] Trial 112 finished with value: -1.4796998278791198 and parameters: {'EMA_S': 26, 'EMA_L': 58}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:31,048] Trial 113 finished with value: -1.2928530624521966 and parameters: {'EMA_S': 22, 'EMA_L': 65}. Best is trial 60 with value: -1.7405452191273518.
[I 2025-07-29 20:57:31,132] Trial 114 finished with value: -1.429372999299851 and parameters: {'EMA_S': 34, 'EMA_L': 52}. Best is trial 60 with value: -1.7405452191273518.

Optuna optimization completed.
Best Parameters (EMA/SMA): EMA_S = 21, EMA_L = 39
Best Multiple: 1.748291
====================================================================================================
EMA/SMA STRATEGY | INSTRUMENT = GBP_USD
----------------------------------------------------------------------------------------------------
PERFORMANCE MEASURES:


Multiple (Strategy):         1.748291
Multiple (Buy-and-Hold):     1.181254
--------------------------------------
Out-/Underperformance:       0.567037


CAGR:                        0.035957
Annualized Mean:             0.035453
Annualized Std:              0.122549
Sharpe Ratio:                0.289292
Sortino Ratio:               0.510277
Maximum Drawdown:            0.321835
Calmar Ratio:                0.111726
Max Drawdown Duration:       1746 Days
Kelly Criterion:             2.726962
====================================================================================================

In [20]:
tester.add_leverage(2)

====================================================================================================
EMA/SMA + RSI COMBINED STRATEGY | INSTRUMENT = GBP_USD
----------------------------------------------------------------------------------------------------
PERFORMANCE MEASURES:


Multiple (Strategy):         1.950461
Multiple (Buy-and-Hold):     1.181254
--------------------------------------
Out-/Underperformance:       0.769207


CAGR:                        0.043151
Annualized Mean:             0.042397
Annualized Std:              0.23601
Sharpe Ratio:                0.179641
Sortino Ratio:               0.300472
Maximum Drawdown:            0.562467
Calmar Ratio:                0.076717
Max Drawdown Duration:       2036 Days
Kelly Criterion:             1.18031
====================================================================================================

4. Testing RSI

In [21]:
tester.optimize_parameters_optuna(EMA1_range=(20, 100, 1), EMA2_range=(20, 100, 1), periods_range=(5, 20, 1), rsi_upper_range=(65, 80, 1),rsi_lower_range=(20, 35, 1), metric="Multiple", n_trials=1000, mode="rsi")

[I 2025-07-29 20:59:37,289] A new study created in memory with name: no-name-348e072f-c324-446d-bb94-f251d2865290
[I 2025-07-29 20:59:37,380] Trial 0 finished with value: -0.4946769473820032 and parameters: {'RSI_periods': 9, 'RSI_upper': 75, 'RSI_lower': 23}. Best is trial 0 with value: -0.4946769473820032.
[I 2025-07-29 20:59:37,453] Trial 1 finished with value: -0.4020291367797875 and parameters: {'RSI_periods': 16, 'RSI_upper': 77, 'RSI_lower': 33}. Best is trial 0 with value: -0.4946769473820032.
[I 2025-07-29 20:59:37,525] Trial 2 finished with value: -0.4363044311017532 and parameters: {'RSI_periods': 16, 'RSI_upper': 73, 'RSI_lower': 23}. Best is trial 0 with value: -0.4946769473820032.
[I 2025-07-29 20:59:37,588] Trial 3 finished with value: -0.18991815330250555 and parameters: {'RSI_periods': 5, 'RSI_upper': 77, 'RSI_lower': 34}. Best is trial 0 with value: -0.4946769473820032.
[I 2025-07-29 20:59:37,658] Trial 4 finished with value: -0.40263043435609824 and parameters: {'RSI_periods': 13, 'RSI_upper': 70, 'RSI_lower': 27}. Best is trial 0 with value: -0.4946769473820032.
[I 2025-07-29 20:59:37,716] Trial 5 finished with value: -0.17988618249043165 and parameters: {'RSI_periods': 5, 'RSI_upper': 74, 'RSI_lower': 22}. Best is trial 0 with value: -0.4946769473820032.
[I 2025-07-29 20:59:37,784] Trial 6 finished with value: -0.4706368316510854 and parameters: {'RSI_periods': 17, 'RSI_upper': 71, 'RSI_lower': 32}. Best is trial 0 with value: -0.4946769473820032.
[I 2025-07-29 20:59:37,861] Trial 7 finished with value: -0.4307753785816468 and parameters: {'RSI_periods': 12, 'RSI_upper': 73, 'RSI_lower': 32}. Best is trial 0 with value: -0.4946769473820032.
[I 2025-07-29 20:59:37,934] Trial 8 finished with value: -0.4720226485851388 and parameters: {'RSI_periods': 11, 'RSI_upper': 74, 'RSI_lower': 29}. Best is trial 0 with value: -0.4946769473820032.
[I 2025-07-29 20:59:38,011] Trial 9 finished with value: -0.5320826832485122 and parameters: {'RSI_periods': 13, 'RSI_upper': 78, 'RSI_lower': 25}. Best is trial 9 with value: -0.5320826832485122.
[I 2025-07-29 20:59:38,118] Trial 10 finished with value: -0.3503827713189502 and parameters: {'RSI_periods': 8, 'RSI_upper': 65, 'RSI_lower': 26}. Best is trial 9 with value: -0.5320826832485122.
[I 2025-07-29 20:59:38,232] Trial 11 finished with value: -0.6660332137637057 and parameters: {'RSI_periods': 9, 'RSI_upper': 78, 'RSI_lower': 20}. Best is trial 11 with value: -0.6660332137637057.
[I 2025-07-29 20:59:38,452] Trial 12 finished with value: -0.6486177821761037 and parameters: {'RSI_periods': 14, 'RSI_upper': 79, 'RSI_lower': 20}. Best is trial 11 with value: -0.6660332137637057.
[I 2025-07-29 20:59:38,558] Trial 13 finished with value: -0.6691224168682308 and parameters: {'RSI_periods': 19, 'RSI_upper': 79, 'RSI_lower': 20}. Best is trial 13 with value: -0.6691224168682308.
[I 2025-07-29 20:59:38,635] Trial 14 finished with value: -0.6691224168682308 and parameters: {'RSI_periods': 19, 'RSI_upper': 79, 'RSI_lower': 20}. Best is trial 13 with value: -0.6691224168682308.
[I 2025-07-29 20:59:38,704] Trial 15 finished with value: -0.5183990497769884 and parameters: {'RSI_periods': 19, 'RSI_upper': 68, 'RSI_lower': 21}. Best is trial 13 with value: -0.6691224168682308.
[I 2025-07-29 20:59:38,772] Trial 16 finished with value: -0.5465777197850139 and parameters: {'RSI_periods': 19, 'RSI_upper': 76, 'RSI_lower': 24}. Best is trial 13 with value: -0.6691224168682308.
[I 2025-07-29 20:59:38,831] Trial 17 finished with value: -0.5702022924047891 and parameters: {'RSI_periods': 18, 'RSI_upper': 79, 'RSI_lower': 29}. Best is trial 13 with value: -0.6691224168682308.
[I 2025-07-29 20:59:38,916] Trial 18 finished with value: -0.5486458948231725 and parameters: {'RSI_periods': 15, 'RSI_upper': 76, 'RSI_lower': 22}. Best is trial 13 with value: -0.6691224168682308.
[I 2025-07-29 20:59:38,997] Trial 19 finished with value: -0.5163733135759045 and parameters: {'RSI_periods': 17, 'RSI_upper': 69, 'RSI_lower': 20}. Best is trial 13 with value: -0.6691224168682308.
[I 2025-07-29 20:59:39,065] Trial 20 finished with value: -0.4815658917989322 and parameters: {'RSI_periods': 19, 'RSI_upper': 67, 'RSI_lower': 25}. Best is trial 13 with value: -0.6691224168682308.
[I 2025-07-29 20:59:39,138] Trial 21 finished with value: -0.6669664486399797 and parameters: {'RSI_periods': 9, 'RSI_upper': 79, 'RSI_lower': 20}. Best is trial 13 with value: -0.6691224168682308.
[I 2025-07-29 20:59:39,216] Trial 22 finished with value: -0.6689667542970522 and parameters: {'RSI_periods': 8, 'RSI_upper': 79, 'RSI_lower': 22}. Best is trial 13 with value: -0.6691224168682308.
[I 2025-07-29 20:59:39,294] Trial 23 finished with value: -0.42059079524690945 and parameters: {'RSI_periods': 7, 'RSI_upper': 77, 'RSI_lower': 22}. Best is trial 13 with value: -0.6691224168682308.
[I 2025-07-29 20:59:39,369] Trial 24 finished with value: -0.7893529319757098 and parameters: {'RSI_periods': 11, 'RSI_upper': 78, 'RSI_lower': 21}. Best is trial 24 with value: -0.7893529319757098.
[I 2025-07-29 20:59:39,439] Trial 25 finished with value: -0.7606090810622479 and parameters: {'RSI_periods': 11, 'RSI_upper': 76, 'RSI_lower': 21}. Best is trial 24 with value: -0.7893529319757098.
[I 2025-07-29 20:59:39,511] Trial 26 finished with value: -0.5852363491675441 and parameters: {'RSI_periods': 11, 'RSI_upper': 75, 'RSI_lower': 24}. Best is trial 24 with value: -0.7893529319757098.
[I 2025-07-29 20:59:39,606] Trial 27 finished with value: -0.5394378473060157 and parameters: {'RSI_periods': 11, 'RSI_upper': 76, 'RSI_lower': 29}. Best is trial 24 with value: -0.7893529319757098.
[I 2025-07-29 20:59:39,682] Trial 28 finished with value: -0.6970501809724069 and parameters: {'RSI_periods': 10, 'RSI_upper': 78, 'RSI_lower': 21}. Best is trial 24 with value: -0.7893529319757098.
[I 2025-07-29 20:59:39,756] Trial 29 finished with value: -0.5561152113176341 and parameters: {'RSI_periods': 10, 'RSI_upper': 75, 'RSI_lower': 23}. Best is trial 24 with value: -0.7893529319757098.
[I 2025-07-29 20:59:39,831] Trial 30 finished with value: -0.7651074908403804 and parameters: {'RSI_periods': 12, 'RSI_upper': 77, 'RSI_lower': 21}. Best is trial 24 with value: -0.7893529319757098.
[I 2025-07-29 20:59:39,905] Trial 31 finished with value: -0.7727178691418936 and parameters: {'RSI_periods': 12, 'RSI_upper': 78, 'RSI_lower': 21}. Best is trial 24 with value: -0.7893529319757098.
[I 2025-07-29 20:59:39,981] Trial 32 finished with value: -0.6187863279572202 and parameters: {'RSI_periods': 13, 'RSI_upper': 77, 'RSI_lower': 23}. Best is trial 24 with value: -0.7893529319757098.
[I 2025-07-29 20:59:40,038] Trial 33 finished with value: -0.688874994495845 and parameters: {'RSI_periods': 12, 'RSI_upper': 76, 'RSI_lower': 21}. Best is trial 24 with value: -0.7893529319757098.
[I 2025-07-29 20:59:40,115] Trial 34 finished with value: -0.5030033068698742 and parameters: {'RSI_periods': 14, 'RSI_upper': 77, 'RSI_lower': 24}. Best is trial 24 with value: -0.7893529319757098.
[I 2025-07-29 20:59:40,188] Trial 35 finished with value: -0.6362966517791502 and parameters: {'RSI_periods': 12, 'RSI_upper': 72, 'RSI_lower': 21}. Best is trial 24 with value: -0.7893529319757098.
[I 2025-07-29 20:59:40,258] Trial 36 finished with value: -0.5440612824816087 and parameters: {'RSI_periods': 10, 'RSI_upper': 74, 'RSI_lower': 22}. Best is trial 24 with value: -0.7893529319757098.
[I 2025-07-29 20:59:40,338] Trial 37 finished with value: -0.5412119296880396 and parameters: {'RSI_periods': 15, 'RSI_upper': 78, 'RSI_lower': 23}. Best is trial 24 with value: -0.7893529319757098.
[I 2025-07-29 20:59:40,405] Trial 38 finished with value: -0.5250277185701601 and parameters: {'RSI_periods': 13, 'RSI_upper': 75, 'RSI_lower': 21}. Best is trial 24 with value: -0.7893529319757098.
[I 2025-07-29 20:59:40,488] Trial 39 finished with value: -0.4912824784342154 and parameters: {'RSI_periods': 11, 'RSI_upper': 73, 'RSI_lower': 27}. Best is trial 24 with value: -0.7893529319757098.
[I 2025-07-29 20:59:40,577] Trial 40 finished with value: -0.5440380272368673 and parameters: {'RSI_periods': 14, 'RSI_upper': 77, 'RSI_lower': 22}. Best is trial 24 with value: -0.7893529319757098.
[I 2025-07-29 20:59:40,639] Trial 41 finished with value: -0.6970501809724069 and parameters: {'RSI_periods': 10, 'RSI_upper': 78, 'RSI_lower': 21}. Best is trial 24 with value: -0.7893529319757098.
[I 2025-07-29 20:59:40,722] Trial 42 finished with value: -0.7727178691418936 and parameters: {'RSI_periods': 12, 'RSI_upper': 78, 'RSI_lower': 21}. Best is trial 24 with value: -0.7893529319757098.
[I 2025-07-29 20:59:40,789] Trial 43 finished with value: -0.7505353598060329 and parameters: {'RSI_periods': 12, 'RSI_upper': 77, 'RSI_lower': 23}. Best is trial 24 with value: -0.7893529319757098.
[I 2025-07-29 20:59:40,864] Trial 44 finished with value: -0.6964123586907139 and parameters: {'RSI_periods': 12, 'RSI_upper': 78, 'RSI_lower': 25}. Best is trial 24 with value: -0.7893529319757098.
[I 2025-07-29 20:59:40,938] Trial 45 finished with value: -0.7243977937036226 and parameters: {'RSI_periods': 11, 'RSI_upper': 76, 'RSI_lower': 22}. Best is trial 24 with value: -0.7893529319757098.
[I 2025-07-29 20:59:40,995] Trial 46 finished with value: -0.4258037913571661 and parameters: {'RSI_periods': 13, 'RSI_upper': 74, 'RSI_lower': 31}. Best is trial 24 with value: -0.7893529319757098.
[I 2025-07-29 20:59:41,065] Trial 47 finished with value: -0.4227815065995186 and parameters: {'RSI_periods': 9, 'RSI_upper': 78, 'RSI_lower': 34}. Best is trial 24 with value: -0.7893529319757098.
[I 2025-07-29 20:59:41,190] Trial 48 finished with value: -0.5236503103123378 and parameters: {'RSI_periods': 15, 'RSI_upper': 71, 'RSI_lower': 21}. Best is trial 24 with value: -0.7893529319757098.
[I 2025-07-29 20:59:41,299] Trial 49 finished with value: -0.6154107082253517 and parameters: {'RSI_periods': 8, 'RSI_upper': 77, 'RSI_lower': 20}. Best is trial 24 with value: -0.7893529319757098.
[I 2025-07-29 20:59:41,383] Trial 50 finished with value: -0.48029370997540966 and parameters: {'RSI_periods': 13, 'RSI_upper': 76, 'RSI_lower': 24}. Best is trial 24 with value: -0.7893529319757098.
[I 2025-07-29 20:59:41,469] Trial 51 finished with value: -0.7505353598060329 and parameters: {'RSI_periods': 12, 'RSI_upper': 77, 'RSI_lower': 23}. Best is trial 24 with value: -0.7893529319757098.
[I 2025-07-29 20:59:41,549] Trial 52 finished with value: -0.7727178691418936 and parameters: {'RSI_periods': 12, 'RSI_upper': 78, 'RSI_lower': 21}. Best is trial 24 with value: -0.7893529319757098.
[I 2025-07-29 20:59:41,640] Trial 53 finished with value: -0.7893529319757098 and parameters: {'RSI_periods': 11, 'RSI_upper': 78, 'RSI_lower': 21}. Best is trial 24 with value: -0.7893529319757098.
[I 2025-07-29 20:59:41,712] Trial 54 finished with value: -0.6223213790425116 and parameters: {'RSI_periods': 14, 'RSI_upper': 78, 'RSI_lower': 20}. Best is trial 24 with value: -0.7893529319757098.
[I 2025-07-29 20:59:41,778] Trial 55 finished with value: -0.6758256835453809 and parameters: {'RSI_periods': 10, 'RSI_upper': 79, 'RSI_lower': 22}. Best is trial 24 with value: -0.7893529319757098.
[I 2025-07-29 20:59:41,866] Trial 56 finished with value: -0.7832405886151447 and parameters: {'RSI_periods': 12, 'RSI_upper': 79, 'RSI_lower': 20}. Best is trial 24 with value: -0.7893529319757098.
[I 2025-07-29 20:59:41,948] Trial 57 finished with value: -0.8803347814660272 and parameters: {'RSI_periods': 11, 'RSI_upper': 79, 'RSI_lower': 20}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:42,021] Trial 58 finished with value: -0.8803347814660272 and parameters: {'RSI_periods': 11, 'RSI_upper': 79, 'RSI_lower': 20}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:42,098] Trial 59 finished with value: -0.8803347814660272 and parameters: {'RSI_periods': 11, 'RSI_upper': 79, 'RSI_lower': 20}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:42,162] Trial 60 finished with value: -0.6669664486399797 and parameters: {'RSI_periods': 9, 'RSI_upper': 79, 'RSI_lower': 20}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:42,238] Trial 61 finished with value: -0.8803347814660272 and parameters: {'RSI_periods': 11, 'RSI_upper': 79, 'RSI_lower': 20}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:42,311] Trial 62 finished with value: -0.8803347814660272 and parameters: {'RSI_periods': 11, 'RSI_upper': 79, 'RSI_lower': 20}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:42,388] Trial 63 finished with value: -0.8803347814660272 and parameters: {'RSI_periods': 11, 'RSI_upper': 79, 'RSI_lower': 20}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:42,471] Trial 64 finished with value: -0.746722563489121 and parameters: {'RSI_periods': 10, 'RSI_upper': 79, 'RSI_lower': 20}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:42,541] Trial 65 finished with value: -0.8803347814660272 and parameters: {'RSI_periods': 11, 'RSI_upper': 79, 'RSI_lower': 20}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:42,625] Trial 66 finished with value: -0.8803347814660272 and parameters: {'RSI_periods': 11, 'RSI_upper': 79, 'RSI_lower': 20}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:42,704] Trial 67 finished with value: -0.6439832476590056 and parameters: {'RSI_periods': 8, 'RSI_upper': 79, 'RSI_lower': 20}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:42,772] Trial 68 finished with value: -0.474097140894653 and parameters: {'RSI_periods': 9, 'RSI_upper': 79, 'RSI_lower': 30}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:42,845] Trial 69 finished with value: -0.36942316418664267 and parameters: {'RSI_periods': 10, 'RSI_upper': 66, 'RSI_lower': 33}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:42,911] Trial 70 finished with value: -0.2972827432688567 and parameters: {'RSI_periods': 6, 'RSI_upper': 79, 'RSI_lower': 20}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:42,988] Trial 71 finished with value: -0.8803347814660272 and parameters: {'RSI_periods': 11, 'RSI_upper': 79, 'RSI_lower': 20}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:43,072] Trial 72 finished with value: -0.8803347814660272 and parameters: {'RSI_periods': 11, 'RSI_upper': 79, 'RSI_lower': 20}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:43,140] Trial 73 finished with value: -0.746722563489121 and parameters: {'RSI_periods': 10, 'RSI_upper': 79, 'RSI_lower': 20}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:43,213] Trial 74 finished with value: -0.8306793815733537 and parameters: {'RSI_periods': 11, 'RSI_upper': 78, 'RSI_lower': 20}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:43,299] Trial 75 finished with value: -0.6758256835453809 and parameters: {'RSI_periods': 10, 'RSI_upper': 79, 'RSI_lower': 22}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:43,382] Trial 76 finished with value: -0.5937116892815105 and parameters: {'RSI_periods': 11, 'RSI_upper': 78, 'RSI_lower': 27}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:43,468] Trial 77 finished with value: -0.4732049291178009 and parameters: {'RSI_periods': 9, 'RSI_upper': 69, 'RSI_lower': 22}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:43,592] Trial 78 finished with value: -0.8365379667354138 and parameters: {'RSI_periods': 11, 'RSI_upper': 79, 'RSI_lower': 21}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:43,747] Trial 79 finished with value: -0.5079794306062106 and parameters: {'RSI_periods': 13, 'RSI_upper': 78, 'RSI_lower': 26}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:43,822] Trial 80 finished with value: -0.746722563489121 and parameters: {'RSI_periods': 10, 'RSI_upper': 79, 'RSI_lower': 20}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:43,905] Trial 81 finished with value: -0.8803347814660272 and parameters: {'RSI_periods': 11, 'RSI_upper': 79, 'RSI_lower': 20}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:43,964] Trial 82 finished with value: -0.8803347814660272 and parameters: {'RSI_periods': 11, 'RSI_upper': 79, 'RSI_lower': 20}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:44,038] Trial 83 finished with value: -0.7820475404262905 and parameters: {'RSI_periods': 11, 'RSI_upper': 77, 'RSI_lower': 21}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:44,115] Trial 84 finished with value: -0.5996638343679763 and parameters: {'RSI_periods': 12, 'RSI_upper': 78, 'RSI_lower': 28}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:44,198] Trial 85 finished with value: -0.7341365402327685 and parameters: {'RSI_periods': 10, 'RSI_upper': 79, 'RSI_lower': 21}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:44,284] Trial 86 finished with value: -0.8306793815733537 and parameters: {'RSI_periods': 11, 'RSI_upper': 78, 'RSI_lower': 20}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:44,365] Trial 87 finished with value: -0.6660332137637057 and parameters: {'RSI_periods': 9, 'RSI_upper': 78, 'RSI_lower': 20}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:44,445] Trial 88 finished with value: -0.7767708260021452 and parameters: {'RSI_periods': 12, 'RSI_upper': 79, 'RSI_lower': 21}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:44,540] Trial 89 finished with value: -0.6852791185767186 and parameters: {'RSI_periods': 10, 'RSI_upper': 77, 'RSI_lower': 20}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:44,625] Trial 90 finished with value: -0.7636618490947998 and parameters: {'RSI_periods': 12, 'RSI_upper': 79, 'RSI_lower': 22}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:44,688] Trial 91 finished with value: -0.8803347814660272 and parameters: {'RSI_periods': 11, 'RSI_upper': 79, 'RSI_lower': 20}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:44,755] Trial 92 finished with value: -0.8365379667354138 and parameters: {'RSI_periods': 11, 'RSI_upper': 79, 'RSI_lower': 21}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:44,828] Trial 93 finished with value: -0.8803347814660272 and parameters: {'RSI_periods': 11, 'RSI_upper': 79, 'RSI_lower': 20}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:44,908] Trial 94 finished with value: -0.6970501809724069 and parameters: {'RSI_periods': 10, 'RSI_upper': 78, 'RSI_lower': 21}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:44,978] Trial 95 finished with value: -0.7791538744768274 and parameters: {'RSI_periods': 12, 'RSI_upper': 78, 'RSI_lower': 20}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:45,045] Trial 96 finished with value: -0.8365379667354138 and parameters: {'RSI_periods': 11, 'RSI_upper': 79, 'RSI_lower': 21}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:45,114] Trial 97 finished with value: -0.5940875970618053 and parameters: {'RSI_periods': 13, 'RSI_upper': 78, 'RSI_lower': 20}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:45,212] Trial 98 finished with value: -0.746722563489121 and parameters: {'RSI_periods': 10, 'RSI_upper': 79, 'RSI_lower': 20}. Best is trial 57 with value: -0.8803347814660272.
[I 2025-07-29 20:59:45,298] Trial 99 finished with value: -0.7651074908403804 and parameters: {'RSI_periods': 12, 'RSI_upper': 77, 'RSI_lower': 21}. Best is trial 57 with value: -0.8803347814660272.

Optuna optimization completed.
Best Parameters (RSI): RSI_periods = 11, RSI_upper = 79, RSI_lower = 20
Best Multiple: 0.880335
====================================================================================================
RSI STRATEGY | INSTRUMENT = GBP_USD
----------------------------------------------------------------------------------------------------
PERFORMANCE MEASURES:


Multiple (Strategy):         0.880335
Multiple (Buy-and-Hold):     1.181254
--------------------------------------
Out-/Underperformance:       -0.300919


CAGR:                        -0.008027
Annualized Mean:             -0.008092
Annualized Std:              0.080454
Sharpe Ratio:                -0.100574
Sortino Ratio:               -0.168695
Maximum Drawdown:            0.372376
Calmar Ratio:                -0.021557
Max Drawdown Duration:       3633 Days
Kelly Criterion:             -0.699571
====================================================================================================

5. Testing EMA+RSI

In [22]:
tester.optimize_parameters_optuna(EMA1_range=(20, 100, 1), EMA2_range=(20, 100, 1), periods_range=(5, 20, 1), rsi_upper_range=(65, 80, 1),rsi_lower_range=(20, 35, 1), metric="Multiple", n_trials=1000, mode="ema_rsi_combined")

[I 2025-07-29 21:02:00,259] A new study created in memory with name: no-name-ece548cf-c087-4f02-826a-ea2aa86996ab
[I 2025-07-29 21:02:00,329] Trial 0 finished with value: -0.8073217537127432 and parameters: {'EMA_S': 24, 'EMA_L': 24, 'RSI_periods': 12, 'RSI_upper': 79, 'RSI_lower': 25}. Best is trial 0 with value: -0.8073217537127432.
[I 2025-07-29 21:02:00,397] Trial 1 finished with value: -0.6305018502722355 and parameters: {'EMA_S': 95, 'EMA_L': 67, 'RSI_periods': 14, 'RSI_upper': 79, 'RSI_lower': 26}. Best is trial 0 with value: -0.8073217537127432.
[I 2025-07-29 21:02:00,455] Trial 2 finished with value: -0.7292312025417598 and parameters: {'EMA_S': 46, 'EMA_L': 99, 'RSI_periods': 16, 'RSI_upper': 71, 'RSI_lower': 22}. Best is trial 0 with value: -0.8073217537127432.
[I 2025-07-29 21:02:00,512] Trial 3 finished with value: -0.3209834224318172 and parameters: {'EMA_S': 80, 'EMA_L': 61, 'RSI_periods': 5, 'RSI_upper': 67, 'RSI_lower': 28}. Best is trial 0 with value: -0.8073217537127432.
[I 2025-07-29 21:02:00,596] Trial 4 finished with value: -0.849953254236745 and parameters: {'EMA_S': 27, 'EMA_L': 64, 'RSI_periods': 15, 'RSI_upper': 71, 'RSI_lower': 23}. Best is trial 4 with value: -0.849953254236745.
[I 2025-07-29 21:02:00,662] Trial 5 finished with value: -0.39726903116204043 and parameters: {'EMA_S': 38, 'EMA_L': 24, 'RSI_periods': 8, 'RSI_upper': 72, 'RSI_lower': 27}. Best is trial 4 with value: -0.849953254236745.
[I 2025-07-29 21:02:00,733] Trial 6 finished with value: -0.6286589150663794 and parameters: {'EMA_S': 44, 'EMA_L': 70, 'RSI_periods': 14, 'RSI_upper': 68, 'RSI_lower': 27}. Best is trial 4 with value: -0.849953254236745.
[I 2025-07-29 21:02:00,818] Trial 7 finished with value: -0.5458961675744575 and parameters: {'EMA_S': 56, 'EMA_L': 96, 'RSI_periods': 6, 'RSI_upper': 78, 'RSI_lower': 24}. Best is trial 4 with value: -0.849953254236745.
[I 2025-07-29 21:02:00,931] Trial 8 finished with value: -0.4941501458326912 and parameters: {'EMA_S': 90, 'EMA_L': 87, 'RSI_periods': 11, 'RSI_upper': 68, 'RSI_lower': 32}. Best is trial 4 with value: -0.849953254236745.
[I 2025-07-29 21:02:01,105] Trial 9 finished with value: -0.481346208346766 and parameters: {'EMA_S': 85, 'EMA_L': 41, 'RSI_periods': 7, 'RSI_upper': 73, 'RSI_lower': 33}. Best is trial 4 with value: -0.849953254236745.
[I 2025-07-29 21:02:01,361] Trial 10 finished with value: -0.989229206417115 and parameters: {'EMA_S': 20, 'EMA_L': 45, 'RSI_periods': 19, 'RSI_upper': 75, 'RSI_lower': 20}. Best is trial 10 with value: -0.989229206417115.
[I 2025-07-29 21:02:01,510] Trial 11 finished with value: -0.9742915123899772 and parameters: {'EMA_S': 23, 'EMA_L': 46, 'RSI_periods': 19, 'RSI_upper': 75, 'RSI_lower': 20}. Best is trial 10 with value: -0.989229206417115.
[I 2025-07-29 21:02:01,594] Trial 12 finished with value: -0.989229206417115 and parameters: {'EMA_S': 20, 'EMA_L': 45, 'RSI_periods': 19, 'RSI_upper': 75, 'RSI_lower': 20}. Best is trial 10 with value: -0.989229206417115.
[I 2025-07-29 21:02:01,669] Trial 13 finished with value: -0.7936774512917183 and parameters: {'EMA_S': 70, 'EMA_L': 44, 'RSI_periods': 19, 'RSI_upper': 76, 'RSI_lower': 20}. Best is trial 10 with value: -0.989229206417115.
[I 2025-07-29 21:02:01,753] Trial 14 finished with value: -0.5237442046542957 and parameters: {'EMA_S': 37, 'EMA_L': 35, 'RSI_periods': 17, 'RSI_upper': 75, 'RSI_lower': 30}. Best is trial 10 with value: -0.989229206417115.
[I 2025-07-29 21:02:01,840] Trial 15 finished with value: -0.7395741134101091 and parameters: {'EMA_S': 58, 'EMA_L': 53, 'RSI_periods': 18, 'RSI_upper': 77, 'RSI_lower': 22}. Best is trial 10 with value: -0.989229206417115.
[I 2025-07-29 21:02:01,920] Trial 16 finished with value: -1.2016694612114573 and parameters: {'EMA_S': 20, 'EMA_L': 31, 'RSI_periods': 10, 'RSI_upper': 74, 'RSI_lower': 20}. Best is trial 16 with value: -1.2016694612114573.
[I 2025-07-29 21:02:02,018] Trial 17 finished with value: -0.4621480226452114 and parameters: {'EMA_S': 34, 'EMA_L': 33, 'RSI_periods': 10, 'RSI_upper': 65, 'RSI_lower': 22}. Best is trial 16 with value: -1.2016694612114573.
[I 2025-07-29 21:02:02,101] Trial 18 finished with value: -0.6620260456314866 and parameters: {'EMA_S': 51, 'EMA_L': 78, 'RSI_periods': 9, 'RSI_upper': 73, 'RSI_lower': 29}. Best is trial 16 with value: -1.2016694612114573.
[I 2025-07-29 21:02:02,201] Trial 19 finished with value: -0.47099295531384433 and parameters: {'EMA_S': 33, 'EMA_L': 32, 'RSI_periods': 13, 'RSI_upper': 74, 'RSI_lower': 24}. Best is trial 16 with value: -1.2016694612114573.
[I 2025-07-29 21:02:02,293] Trial 20 finished with value: -0.5936107766194213 and parameters: {'EMA_S': 67, 'EMA_L': 54, 'RSI_periods': 11, 'RSI_upper': 70, 'RSI_lower': 21}. Best is trial 16 with value: -1.2016694612114573.
[I 2025-07-29 21:02:02,371] Trial 21 finished with value: -0.9292693183612059 and parameters: {'EMA_S': 29, 'EMA_L': 51, 'RSI_periods': 16, 'RSI_upper': 75, 'RSI_lower': 20}. Best is trial 16 with value: -1.2016694612114573.
[I 2025-07-29 21:02:02,461] Trial 22 finished with value: -0.9280984521083487 and parameters: {'EMA_S': 20, 'EMA_L': 39, 'RSI_periods': 17, 'RSI_upper': 77, 'RSI_lower': 21}. Best is trial 16 with value: -1.2016694612114573.
[I 2025-07-29 21:02:02,540] Trial 23 finished with value: -0.5442346155214728 and parameters: {'EMA_S': 21, 'EMA_L': 20, 'RSI_periods': 18, 'RSI_upper': 74, 'RSI_lower': 23}. Best is trial 16 with value: -1.2016694612114573.
[I 2025-07-29 21:02:02,634] Trial 24 finished with value: -1.1737121750770259 and parameters: {'EMA_S': 29, 'EMA_L': 30, 'RSI_periods': 9, 'RSI_upper': 76, 'RSI_lower': 20}. Best is trial 16 with value: -1.2016694612114573.
[I 2025-07-29 21:02:02,717] Trial 25 finished with value: -0.476534309470448 and parameters: {'EMA_S': 31, 'EMA_L': 30, 'RSI_periods': 9, 'RSI_upper': 77, 'RSI_lower': 21}. Best is trial 16 with value: -1.2016694612114573.
[I 2025-07-29 21:02:02,793] Trial 26 finished with value: -0.4342242743896289 and parameters: {'EMA_S': 43, 'EMA_L': 27, 'RSI_periods': 8, 'RSI_upper': 73, 'RSI_lower': 23}. Best is trial 16 with value: -1.2016694612114573.
[I 2025-07-29 21:02:02,880] Trial 27 finished with value: -1.3387010977282008 and parameters: {'EMA_S': 28, 'EMA_L': 38, 'RSI_periods': 11, 'RSI_upper': 76, 'RSI_lower': 25}. Best is trial 27 with value: -1.3387010977282008.
[I 2025-07-29 21:02:02,962] Trial 28 finished with value: -1.3387010977282008 and parameters: {'EMA_S': 28, 'EMA_L': 38, 'RSI_periods': 11, 'RSI_upper': 76, 'RSI_lower': 25}. Best is trial 27 with value: -1.3387010977282008.
[I 2025-07-29 21:02:03,049] Trial 29 finished with value: -0.496439132986542 and parameters: {'EMA_S': 39, 'EMA_L': 21, 'RSI_periods': 12, 'RSI_upper': 79, 'RSI_lower': 25}. Best is trial 27 with value: -1.3387010977282008.
[I 2025-07-29 21:02:03,131] Trial 30 finished with value: -0.49318743125714415 and parameters: {'EMA_S': 51, 'EMA_L': 37, 'RSI_periods': 11, 'RSI_upper': 78, 'RSI_lower': 25}. Best is trial 27 with value: -1.3387010977282008.
[I 2025-07-29 21:02:03,221] Trial 31 finished with value: -1.1257921632664254 and parameters: {'EMA_S': 26, 'EMA_L': 27, 'RSI_periods': 10, 'RSI_upper': 76, 'RSI_lower': 26}. Best is trial 27 with value: -1.3387010977282008.
[I 2025-07-29 21:02:03,314] Trial 32 finished with value: -1.0877241819129562 and parameters: {'EMA_S': 28, 'EMA_L': 29, 'RSI_periods': 13, 'RSI_upper': 76, 'RSI_lower': 26}. Best is trial 27 with value: -1.3387010977282008.
[I 2025-07-29 21:02:03,404] Trial 33 finished with value: -1.2253840810119367 and parameters: {'EMA_S': 33, 'EMA_L': 38, 'RSI_periods': 10, 'RSI_upper': 78, 'RSI_lower': 24}. Best is trial 27 with value: -1.3387010977282008.
[I 2025-07-29 21:02:03,480] Trial 34 finished with value: -1.224771491069684 and parameters: {'EMA_S': 34, 'EMA_L': 38, 'RSI_periods': 10, 'RSI_upper': 79, 'RSI_lower': 24}. Best is trial 27 with value: -1.3387010977282008.
[I 2025-07-29 21:02:03,561] Trial 35 finished with value: -0.9349931178325455 and parameters: {'EMA_S': 48, 'EMA_L': 50, 'RSI_periods': 13, 'RSI_upper': 79, 'RSI_lower': 24}. Best is trial 27 with value: -1.3387010977282008.
[I 2025-07-29 21:02:03,638] Trial 36 finished with value: -0.8031093912879325 and parameters: {'EMA_S': 40, 'EMA_L': 40, 'RSI_periods': 12, 'RSI_upper': 78, 'RSI_lower': 25}. Best is trial 27 with value: -1.3387010977282008.
[I 2025-07-29 21:02:03,732] Trial 37 finished with value: -0.9281649618950977 and parameters: {'EMA_S': 33, 'EMA_L': 59, 'RSI_periods': 8, 'RSI_upper': 78, 'RSI_lower': 27}. Best is trial 27 with value: -1.3387010977282008.
[I 2025-07-29 21:02:03,811] Trial 38 finished with value: -0.7454625805095928 and parameters: {'EMA_S': 64, 'EMA_L': 71, 'RSI_periods': 14, 'RSI_upper': 79, 'RSI_lower': 28}. Best is trial 27 with value: -1.3387010977282008.
[I 2025-07-29 21:02:03,907] Trial 39 finished with value: -0.6212095681561199 and parameters: {'EMA_S': 74, 'EMA_L': 58, 'RSI_periods': 11, 'RSI_upper': 77, 'RSI_lower': 26}. Best is trial 27 with value: -1.3387010977282008.
[I 2025-07-29 21:02:03,987] Trial 40 finished with value: -0.33703628054996954 and parameters: {'EMA_S': 36, 'EMA_L': 35, 'RSI_periods': 5, 'RSI_upper': 78, 'RSI_lower': 24}. Best is trial 27 with value: -1.3387010977282008.
[I 2025-07-29 21:02:04,077] Trial 41 finished with value: -1.073308001208424 and parameters: {'EMA_S': 25, 'EMA_L': 42, 'RSI_periods': 10, 'RSI_upper': 74, 'RSI_lower': 23}. Best is trial 27 with value: -1.3387010977282008.
[I 2025-07-29 21:02:04,175] Trial 42 finished with value: -0.7033362452027776 and parameters: {'EMA_S': 25, 'EMA_L': 25, 'RSI_periods': 10, 'RSI_upper': 77, 'RSI_lower': 28}. Best is trial 27 with value: -1.3387010977282008.
[I 2025-07-29 21:02:04,271] Trial 43 finished with value: -0.8947723928247601 and parameters: {'EMA_S': 41, 'EMA_L': 48, 'RSI_periods': 7, 'RSI_upper': 71, 'RSI_lower': 25}. Best is trial 27 with value: -1.3387010977282008.
[I 2025-07-29 21:02:04,361] Trial 44 finished with value: -1.2612319946434674 and parameters: {'EMA_S': 31, 'EMA_L': 36, 'RSI_periods': 12, 'RSI_upper': 79, 'RSI_lower': 22}. Best is trial 27 with value: -1.3387010977282008.
[I 2025-07-29 21:02:04,461] Trial 45 finished with value: -0.5955213022817092 and parameters: {'EMA_S': 47, 'EMA_L': 37, 'RSI_periods': 12, 'RSI_upper': 79, 'RSI_lower': 23}. Best is trial 27 with value: -1.3387010977282008.
[I 2025-07-29 21:02:04,540] Trial 46 finished with value: -0.7122572515311044 and parameters: {'EMA_S': 95, 'EMA_L': 42, 'RSI_periods': 12, 'RSI_upper': 79, 'RSI_lower': 24}. Best is trial 27 with value: -1.3387010977282008.
[I 2025-07-29 21:02:04,641] Trial 47 finished with value: -1.404736967119977 and parameters: {'EMA_S': 31, 'EMA_L': 38, 'RSI_periods': 11, 'RSI_upper': 78, 'RSI_lower': 22}. Best is trial 47 with value: -1.404736967119977.
[I 2025-07-29 21:02:04,737] Trial 48 finished with value: -1.0123347181071642 and parameters: {'EMA_S': 29, 'EMA_L': 48, 'RSI_periods': 14, 'RSI_upper': 78, 'RSI_lower': 22}. Best is trial 47 with value: -1.404736967119977.
[I 2025-07-29 21:02:04,837] Trial 49 finished with value: -1.2854159939710375 and parameters: {'EMA_S': 37, 'EMA_L': 55, 'RSI_periods': 11, 'RSI_upper': 76, 'RSI_lower': 22}. Best is trial 47 with value: -1.404736967119977.
[I 2025-07-29 21:02:04,921] Trial 50 finished with value: -0.897337492019477 and parameters: {'EMA_S': 37, 'EMA_L': 56, 'RSI_periods': 13, 'RSI_upper': 76, 'RSI_lower': 21}. Best is trial 47 with value: -1.404736967119977.
[I 2025-07-29 21:02:04,994] Trial 51 finished with value: -1.3082681085082142 and parameters: {'EMA_S': 31, 'EMA_L': 64, 'RSI_periods': 11, 'RSI_upper': 77, 'RSI_lower': 22}. Best is trial 47 with value: -1.404736967119977.
[I 2025-07-29 21:02:05,088] Trial 52 finished with value: -1.381918286831378 and parameters: {'EMA_S': 23, 'EMA_L': 64, 'RSI_periods': 11, 'RSI_upper': 77, 'RSI_lower': 22}. Best is trial 47 with value: -1.404736967119977.
[I 2025-07-29 21:02:05,171] Trial 53 finished with value: -1.093214275949643 and parameters: {'EMA_S': 24, 'EMA_L': 65, 'RSI_periods': 11, 'RSI_upper': 76, 'RSI_lower': 31}. Best is trial 47 with value: -1.404736967119977.
[I 2025-07-29 21:02:05,267] Trial 54 finished with value: -1.2702665021982984 and parameters: {'EMA_S': 23, 'EMA_L': 71, 'RSI_periods': 11, 'RSI_upper': 77, 'RSI_lower': 22}. Best is trial 47 with value: -1.404736967119977.
[I 2025-07-29 21:02:05,355] Trial 55 finished with value: -1.1085306507514219 and parameters: {'EMA_S': 27, 'EMA_L': 77, 'RSI_periods': 9, 'RSI_upper': 77, 'RSI_lower': 21}. Best is trial 47 with value: -1.404736967119977.
[I 2025-07-29 21:02:05,454] Trial 56 finished with value: -1.0136384606708502 and parameters: {'EMA_S': 44, 'EMA_L': 62, 'RSI_periods': 11, 'RSI_upper': 75, 'RSI_lower': 23}. Best is trial 47 with value: -1.404736967119977.
[I 2025-07-29 21:02:05,549] Trial 57 finished with value: -0.9177810280571843 and parameters: {'EMA_S': 36, 'EMA_L': 66, 'RSI_periods': 14, 'RSI_upper': 75, 'RSI_lower': 22}. Best is trial 47 with value: -1.404736967119977.
[I 2025-07-29 21:02:05,627] Trial 58 finished with value: -0.9811337255986714 and parameters: {'EMA_S': 31, 'EMA_L': 69, 'RSI_periods': 13, 'RSI_upper': 76, 'RSI_lower': 23}. Best is trial 47 with value: -1.404736967119977.
[I 2025-07-29 21:02:05,725] Trial 59 finished with value: -1.31102471881852 and parameters: {'EMA_S': 23, 'EMA_L': 62, 'RSI_periods': 11, 'RSI_upper': 69, 'RSI_lower': 21}. Best is trial 47 with value: -1.404736967119977.
[I 2025-07-29 21:02:05,835] Trial 60 finished with value: -1.0088415088924374 and parameters: {'EMA_S': 23, 'EMA_L': 75, 'RSI_periods': 8, 'RSI_upper': 69, 'RSI_lower': 21}. Best is trial 47 with value: -1.404736967119977.
[I 2025-07-29 21:02:05,933] Trial 61 finished with value: -1.2622133495134327 and parameters: {'EMA_S': 22, 'EMA_L': 62, 'RSI_periods': 11, 'RSI_upper': 67, 'RSI_lower': 22}. Best is trial 47 with value: -1.404736967119977.
[I 2025-07-29 21:02:06,031] Trial 62 finished with value: -1.0943213761713044 and parameters: {'EMA_S': 27, 'EMA_L': 85, 'RSI_periods': 12, 'RSI_upper': 66, 'RSI_lower': 21}. Best is trial 47 with value: -1.404736967119977.
[I 2025-07-29 21:02:06,121] Trial 63 finished with value: -0.9217410189383418 and parameters: {'EMA_S': 30, 'EMA_L': 54, 'RSI_periods': 9, 'RSI_upper': 69, 'RSI_lower': 22}. Best is trial 47 with value: -1.404736967119977.
[I 2025-07-29 21:02:06,219] Trial 64 finished with value: -0.8863222250844851 and parameters: {'EMA_S': 25, 'EMA_L': 68, 'RSI_periods': 15, 'RSI_upper': 72, 'RSI_lower': 20}. Best is trial 47 with value: -1.404736967119977.
[I 2025-07-29 21:02:06,308] Trial 65 finished with value: -1.3581052118474075 and parameters: {'EMA_S': 20, 'EMA_L': 57, 'RSI_periods': 11, 'RSI_upper': 77, 'RSI_lower': 23}. Best is trial 47 with value: -1.404736967119977.
[I 2025-07-29 21:02:06,403] Trial 66 finished with value: -1.0100562607157215 and parameters: {'EMA_S': 20, 'EMA_L': 74, 'RSI_periods': 12, 'RSI_upper': 77, 'RSI_lower': 34}. Best is trial 47 with value: -1.404736967119977.
[I 2025-07-29 21:02:06,487] Trial 67 finished with value: -1.0516164428085495 and parameters: {'EMA_S': 22, 'EMA_L': 63, 'RSI_periods': 10, 'RSI_upper': 71, 'RSI_lower': 23}. Best is trial 47 with value: -1.404736967119977.
[I 2025-07-29 21:02:06,582] Trial 68 finished with value: -1.206538339680225 and parameters: {'EMA_S': 27, 'EMA_L': 60, 'RSI_periods': 11, 'RSI_upper': 77, 'RSI_lower': 27}. Best is trial 47 with value: -1.404736967119977.
[I 2025-07-29 21:02:06,681] Trial 69 finished with value: -1.0200310449176384 and parameters: {'EMA_S': 32, 'EMA_L': 80, 'RSI_periods': 9, 'RSI_upper': 78, 'RSI_lower': 25}. Best is trial 47 with value: -1.404736967119977.
[I 2025-07-29 21:02:06,781] Trial 70 finished with value: -0.6422580251345804 and parameters: {'EMA_S': 83, 'EMA_L': 57, 'RSI_periods': 10, 'RSI_upper': 74, 'RSI_lower': 21}. Best is trial 47 with value: -1.404736967119977.
[I 2025-07-29 21:02:06,881] Trial 71 finished with value: -1.4086370941572721 and parameters: {'EMA_S': 29, 'EMA_L': 55, 'RSI_periods': 11, 'RSI_upper': 76, 'RSI_lower': 22}. Best is trial 71 with value: -1.4086370941572721.
[I 2025-07-29 21:02:06,981] Trial 72 finished with value: -1.3353092271259208 and parameters: {'EMA_S': 29, 'EMA_L': 52, 'RSI_periods': 11, 'RSI_upper': 75, 'RSI_lower': 23}. Best is trial 71 with value: -1.4086370941572721.
[I 2025-07-29 21:02:07,082] Trial 73 finished with value: -1.0732174791402942 and parameters: {'EMA_S': 28, 'EMA_L': 44, 'RSI_periods': 13, 'RSI_upper': 75, 'RSI_lower': 23}. Best is trial 71 with value: -1.4086370941572721.
[I 2025-07-29 21:02:07,192] Trial 74 finished with value: -1.1568122225612243 and parameters: {'EMA_S': 24, 'EMA_L': 50, 'RSI_periods': 12, 'RSI_upper': 76, 'RSI_lower': 26}. Best is trial 71 with value: -1.4086370941572721.
[I 2025-07-29 21:02:07,282] Trial 75 finished with value: -0.46300101412317224 and parameters: {'EMA_S': 35, 'EMA_L': 33, 'RSI_periods': 10, 'RSI_upper': 73, 'RSI_lower': 24}. Best is trial 71 with value: -1.4086370941572721.
[I 2025-07-29 21:02:07,360] Trial 76 finished with value: -0.6630108304764689 and parameters: {'EMA_S': 91, 'EMA_L': 52, 'RSI_periods': 12, 'RSI_upper': 75, 'RSI_lower': 23}. Best is trial 71 with value: -1.4086370941572721.
[I 2025-07-29 21:02:07,447] Trial 77 finished with value: -1.384970450654117 and parameters: {'EMA_S': 22, 'EMA_L': 46, 'RSI_periods': 11, 'RSI_upper': 76, 'RSI_lower': 25}. Best is trial 71 with value: -1.4086370941572721.
[I 2025-07-29 21:02:07,536] Trial 78 finished with value: -1.1164793994005497 and parameters: {'EMA_S': 20, 'EMA_L': 46, 'RSI_periods': 9, 'RSI_upper': 76, 'RSI_lower': 25}. Best is trial 71 with value: -1.4086370941572721.
[I 2025-07-29 21:02:07,621] Trial 79 finished with value: -0.6209582286173858 and parameters: {'EMA_S': 55, 'EMA_L': 48, 'RSI_periods': 11, 'RSI_upper': 78, 'RSI_lower': 26}. Best is trial 71 with value: -1.4086370941572721.
[I 2025-07-29 21:02:07,718] Trial 80 finished with value: -0.5824207687970688 and parameters: {'EMA_S': 98, 'EMA_L': 40, 'RSI_periods': 10, 'RSI_upper': 74, 'RSI_lower': 25}. Best is trial 71 with value: -1.4086370941572721.
[I 2025-07-29 21:02:07,794] Trial 81 finished with value: -1.3068892735625475 and parameters: {'EMA_S': 25, 'EMA_L': 43, 'RSI_periods': 11, 'RSI_upper': 76, 'RSI_lower': 24}. Best is trial 71 with value: -1.4086370941572721.
[I 2025-07-29 21:02:07,874] Trial 82 finished with value: -1.3421160029936894 and parameters: {'EMA_S': 28, 'EMA_L': 60, 'RSI_periods': 11, 'RSI_upper': 75, 'RSI_lower': 20}. Best is trial 71 with value: -1.4086370941572721.
[I 2025-07-29 21:02:07,953] Trial 83 finished with value: -1.24090338548225 and parameters: {'EMA_S': 27, 'EMA_L': 58, 'RSI_periods': 12, 'RSI_upper': 75, 'RSI_lower': 20}. Best is trial 71 with value: -1.4086370941572721.
[I 2025-07-29 21:02:08,053] Trial 84 finished with value: -1.1910750382265396 and parameters: {'EMA_S': 29, 'EMA_L': 52, 'RSI_periods': 10, 'RSI_upper': 75, 'RSI_lower': 26}. Best is trial 71 with value: -1.4086370941572721.
[I 2025-07-29 21:02:08,141] Trial 85 finished with value: -1.373373318306968 and parameters: {'EMA_S': 34, 'EMA_L': 46, 'RSI_periods': 11, 'RSI_upper': 77, 'RSI_lower': 24}. Best is trial 71 with value: -1.4086370941572721.
[I 2025-07-29 21:02:08,233] Trial 86 finished with value: -0.9902113351771772 and parameters: {'EMA_S': 33, 'EMA_L': 35, 'RSI_periods': 13, 'RSI_upper': 77, 'RSI_lower': 24}. Best is trial 71 with value: -1.4086370941572721.
[I 2025-07-29 21:02:08,321] Trial 87 finished with value: -1.1876608501277555 and parameters: {'EMA_S': 39, 'EMA_L': 47, 'RSI_periods': 12, 'RSI_upper': 77, 'RSI_lower': 25}. Best is trial 71 with value: -1.4086370941572721.

Optuna optimization completed.
Best Parameters (EMA+RSI Combined): EMA_S = 27, EMA_L = 36, RSI_periods = 11, RSI_upper = 79, RSI_lower = 21
Best Multiple: 1.53274
====================================================================================================
EMA/SMA + RSI COMBINED STRATEGY | INSTRUMENT = GBP_USD
----------------------------------------------------------------------------------------------------
PERFORMANCE MEASURES:


Multiple (Strategy):         1.53274
Multiple (Buy-and-Hold):     1.181254
--------------------------------------
Out-/Underperformance:       0.351486


CAGR:                        0.027373
Annualized Mean:             0.027112
Annualized Std:              0.062182
Sharpe Ratio:                0.43602
Sortino Ratio:               2.460203
Maximum Drawdown:            0.075257
Calmar Ratio:                0.363728
Max Drawdown Duration:       2298 Days
Kelly Criterion:             6.562135
====================================================================================================

In [23]:
tester.add_leverage(3)

====================================================================================================
EMA/SMA + RSI COMBINED STRATEGY | INSTRUMENT = GBP_USD
----------------------------------------------------------------------------------------------------
PERFORMANCE MEASURES:


Multiple (Strategy):         2.895101
Multiple (Buy-and-Hold):     1.181254
--------------------------------------
Out-/Underperformance:       1.713847


CAGR:                        0.069532
Annualized Mean:             0.067488
Annualized Std:              0.15737
Sharpe Ratio:                0.428845
Sortino Ratio:               2.032738
Maximum Drawdown:            0.214971
Calmar Ratio:                0.323448
Max Drawdown Duration:       2298 Days
Kelly Criterion:             2.337348
====================================================================================================

In [ ]:
tester.plot_results()